### ISSUE TITLE
souci barre de progression sur import municipalities

### ISSUE THREAD

**Issue by christopheprudent** [BaseAdresseNationale/api-gestion#100]
duplication de la ligne de progression, au lieu d'avoir celle-ci sur une même ligne

Progress: |      | xx% <##/##> | ETA: hh:mm:ss | hh:mm:ss |
Progress: |      | xx% <##/##> | ETA: hh:mm:ss | hh:mm:ss |
...

**Comment by yohanboniface** [comment]
Windows je suppose? :)
Je crois me souvenir que le calcul automatique de la largeur du terminal ne fonctionne pas sur Windows, faut que je trouve un workaround dans la lib dédiée.
Tu peux me faire un screenshot pour que je voie un peu plus à quoi ça ressemble? :)

**Comment by christopheprudent** [comment]
je n'ai plus le job sous la main, mais en effet sous Windows (en mode commande), j'ai plusieurs lignes de progression, qui s'affichent au lieu d'une seule avec la barre de progression et les pourcentages incrémentales

**Comment by yohanboniface** [comment]
A l'occasion, un screenshot me serait utile, pour être sûr de comprendre où ça pèche :)

**Comment by christopheprudent** [comment]
avec le screenshot:
![progressbar](https://cloud.githubusercontent.com/assets/15735397/14528952/78fd651a-0252-11e6-9262-7c02eae83af9.PNG)

**Comment by ebuard** [comment]
Lors de nos derniers tests sous linux, la patience s'affichait correctement.
