### ISSUE TITLE
gestion du CEA pour le cas des voies

### ISSUE THREAD

**Issue by christopheprudent** [BaseAdresseNationale/api-gestion#102]
je pense qu’il y a un ‘:disappointed:-truc’ avec la table Group pour les voies, dans le dernier modèle (sans proxy)
Il y a la colonne ‘laposte’ pour stocker le CEA, mais celui-ci n’est pas unique pour 1 voie (à cause du CP), oops ! même si c’est pratiquement le cas, y’a des exceptions

1 solution serait alors de :
- positionner le CEA de la voie, dans Group, si celle-ci est mono-CP
- créer dans Housenumber autant d’occurrences nécessaires, avec number à NULL en lien avec le CP, et donc à chaque fois le CEA correspondant
  (en fait 2, sauf 1  cas à 3 occurrences : Chemin du Génie à Nice, ça s’invente pas )

Qu’en pensez-vous ?

**Comment by yohanboniface** [comment]
Tu fais toujours référence aux fameuses 53 occurrences du cas 6, i.e. des voies multi-cp mais non numérotées?
Si oui, alors je confirme qu'on avait dit qu'on dupliquerait les 53 housenumbers plutôt que de chambouler toute la modélisation pour ces quelques cas.

**Comment by christopheprudent** [comment]
non, cela concerne ~1000 voies, qui sont distribuées par plus d'1 CP

**Comment by christopheprudent** [comment]
après réflexion, changement à apporter:

- dans Group, pour les voies, stockage du matricule Voie dans l'attribut _laposte_ (présent dans HEXAVIA, et donc utilisé en externe POSTE, notamment à l'IGN), et non plus du CEA

- dans Housenumber, avec astuce number à NULL (en lien avec le postcode), stockage du (ou des, en fonction du nombre de CP) CEA de la voie
cette astuce permet des usages intéressants (affecter une position à un Voie, établir des liens entre éléments de Group, ...)

**Comment by yohanboniface** [comment]
Et il faut que je passe la relation HouseNumber<=>PostCode en one to one :)

**Comment by christopheprudent** [comment]
oui, et à implémenter la partie Certification (MAIRIE, POSTE, IGN, ...), liée à 1 Ressource (Postcode, Group, Housenumber & Position) et à 1 Version

**Comment by yohanboniface** [comment]
> implémenter la partie Certification (MAIRIE, POSTE, IGN, ...), liée à 1 Ressource (Postcode, Group, Housenumber & Position) et à 1 Version

Pour review dans la PR #101 ;)

**Comment by christopheprudent** [comment]
je ne l'avais pas vu, merci

par model Flag, tu entends une nouvelle table ? en lien donc avec Version
et dernière proposition: ajout des flags dans la réponse d'une version, à détailler ? (je ne vois pas bien ce que tu veux dire par là)

**Comment by yohanboniface** [comment]
> par model Flag, tu entends une nouvelle table ? en lien donc avec Version

yep :)

> et dernière proposition: ajout des flags dans la réponse d'une version, à détailler ? (je ne vois pas bien ce que tu veux dire par là)

La JSON de la réponse de l'API ne contient pas les flags pour l'instant. Il faut spécifiquement demander les flags d'une resource pour les lister. Je suis pas sûr de ce qu'on veut.

**Comment by christopheprudent** [comment]
à préciser en effet

sinon, autre cas d'usage à rendre accessible : pouvoir interroger la BAN pour une ressource (ou un ensemble de ressources, du genre liste des voies d'une commune, ...) disposant d'une certification précise

**Comment by cquest** [comment]
Ok, il manque un import du fichier ran_group_ncp.csv

A compléter donc pour l'init...

**Comment by gschittek** [comment]
cf https://github.com/BaseAdresseNationale/donnees-initiales/issues/6
