### ISSUE TITLE
gestion des voies de même libellé dans une commune (souvent après fusion de communes)

### ISSUE THREAD

**Issue by christopheprudent** [BaseAdresseNationale/api-gestion#104]
précision de la #62 
souci de distinction de ces voies homonymes
parfois utile de conserver l'association de ces voies, avec l'ancienne commune, devenue un "quartier" de la nouvelle commune, pour ainsi pouvoir distinguer les 2 voies 

exemple

| INSEE | VOIE | COMMUNE | "QUARTIER" |
| --- | --- | --- | --- |
| 01080 | ROUTE DE BRENOD | CHAMPDOR CORCELLES |  |
| 01080 | ROUTE DE BRENOD | CHAMPDOR CORCELLES | CORCELLES |

**Comment by ebuard** [comment]
Lors de la commande de fusion de communes, les voies portent l'insee de l'ancienne commune dans le champ attributes. Ce qui permet de distinguer 2 voies homonymes suites à une fusion.
