### ISSUE TITLE
métadonnées : sources

### ISSUE THREAD

**Issue by ebuard** [BaseAdresseNationale/api-gestion#139]
Compte tenu du travail de validation, il faudrait spécifier  le plus possible les sources.
Dans l'API, deux infos seront disponibles via le mécanisme de session:
- chacun des services (guichet, crowdsourcing, import AITF, voire autres) aura son propre client de la BAN, et chaque modification est associée (via la session) à ce client
- pour créer une session, le client _doit_ fournir l'email ou bien l'IP du contributeur final, mais il peut aussi attacher des infos supplémentaires s'il le souhaite. 

Que rend t'on disponible via l'API: l'email ou non? Doit-on également renvoyer l'organisme auquel appartient le contributeur, par exemple pour lui donner des droits d'édition de données? Ou de toute façon, les contributeurs passeront par des services, qui lui donneront des droits et rempliront l'organisme associé?

Elodie

**Comment by yohanboniface** [comment]
Voir https://github.com/BaseAdresseNationale/ban/issues/74#issuecomment-254192925 pour explication du fonctionnement actuel.

En l'état, on ne retourne que:
- le user BAN associé à la session, quand il est disponible, ce qui sera rare
- le nom du client BAN associé à la session, ce qui sera le cas le plus courant
- l'identifiant de la session (mais c'est à usage interne seulement)

Quant à l'IP et/ou l'email, je sais pas si on peut (CNIL?) ni veut l'afficher.
Dès lors qu'on est derrière un token même pour un GET, on est dans un espace "privé", donc peut-être qu'on peut se le permettre.
Un point à soulever en réunion d'équipe.

**Comment by ebuard** [comment]
Remplacer par #268
