### ISSUE TITLE
Import BAL : log d'appariement

### ISSUE THREAD

**Issue by MaelREBOUX** [BaseAdresseNationale/api-gestion#141]
Pour les collectivités locales qui voudraient uploader / importer un fichier au standard BAL (Base Adresse Locale) il serait **très** apprécié de récupérer un log d'appariement réalisée lors de l'import.

En effet, il paraît incontournable que les CT vont devoir intégrer l'identifiant unique de voie et d'adresse dans leur base de gestion afin d'assurer et de faciliter la mise à jour de la BAN.

Le minimum serait donc de disposer, après un import d'une BAL d'un log contenant à minima l'identifiant local (plutôt que la clé d'interopérabilité ? A discuter et tester) et l'identifiant national.

**Comment by gschittek** [comment]
L'importation BAL ne passera a priori pas par la commande de l'API
