### ISSUE TITLE
écarts BAN/LaPOSTE sur init (Municipality, Postcode)

### ISSUE THREAD

**Issue by christopheprudent** [BaseAdresseNationale/api-gestion#153]
j'ai commencé à regarder les écarts (BAN / RAN) sur le dump chargé
avec delta=+ (en plus côté BAN), - (en moins) et ! (différent)

voici une première analyse rapide des écarts trouvés

![delta municipality postcode](https://cloud.githubusercontent.com/assets/15735397/16761702/98bf0fa6-4821-11e6-9437-0a0f2540f09f.PNG)
avec un extrait en détail, pour montrer des écarts de libellé
![detail delta municipality](https://cloud.githubusercontent.com/assets/15735397/16761714/a51d44c0-4821-11e6-935d-1f28832c0141.PNG)

concernant le rapprochement, pour Municipality : par rapport au code INSEE
écarts dus à la date des données (sans fusion des communes de 2016, écart aussi sur libellé)

pour Postcode : par rapport au code Postal et au libellé Acheminement 
les écarts CP sont souvent dus à la présence de L5 (anc commune, lieu-dit) sur ces codes
![detail delta postcode - teste de buch](https://cloud.githubusercontent.com/assets/15735397/16761842/43216f84-4822-11e6-9dce-29c5d425803c.PNG)
![detail delta postcode - mauguio](https://cloud.githubusercontent.com/assets/15735397/16761843/4322d57c-4822-11e6-9614-d7312156799f.PNG)

également une différence d'attribution d'un CP sur une commune, ex: CP 34450 pour la commune PORTIRAGNES (INSEE= 34209), qui n'est desservie que par le CP 34420
![detail delta postcode - portiragnes](https://cloud.githubusercontent.com/assets/15735397/16761845/4961ea72-4822-11e6-884f-34dd4b8cc636.PNG)

liste des écarts
[delta-Municipality.txt](https://github.com/BaseAdresseNationale/ban/files/359183/delta-Municipality.txt)
[delta-Postcode.txt](https://github.com/BaseAdresseNationale/ban/files/359184/delta-Postcode.txt)

**Comment by cquest** [comment]
Pour delta-Municipality il y a semble-t-il deux sources d'écarts:
1) la comparaison nom officiel de la commune (issu du COG) et libellé d'acheminement... qui n'est à prendre en compte que sur le postcode, pas sur municipality.
Cette comparaison a-t-elle un sens ?

2) les différences liées au millésime des données: afin de traiter les fusions par les redirections, c'est le COG 2015 qui a été importé et pas encore fait les opérations de fusion, d'où les écarts.
Pour Dévoluy, le nom officiel du COG est sans l'article LE.

**Comment by christopheprudent** [comment]
pour Municipality, tu as raison, je vais recommencer avec le libellé Commune (et non standardisé POSTE)
en appliquant le même algo : en majuscule, sans accent, sans trait d'union, ...

**Comment by christopheprudent** [comment]
j'ai remis à jour le dépôt résultat pour Municipality, dans https://github.com/LaPosteSNA/check-init-of-BAN/tree/master/data

**Comment by christopheprudent** [comment]
t'a vu aussi le souci du caractère 'oe' mal codé
ex: communes INSEE 21132, 17139, ... (Chamboeuf, Doeuil sur le Mignon, ...)

**Comment by cquest** [comment]
J'ai créé une issue pour ça: https://github.com/BaseAdresseNationale/ban/issues/173

**Comment by odorie** [comment]
Je ferme ce ticket au profit du #154 qui donne aussi les écarts BAN/La Poste sur des initialisations plus récentes
