### ISSUE TITLE
écarts BAN/LaPOSTE sur init

### ISSUE THREAD

**Issue by christopheprudent** [BaseAdresseNationale/api-gestion#154]
pas encore de comptage, mais des premiers constats
- libellé BAN avec type de voie abrégé (ALL, AV, BD, SEN, SQ, CHE, RES, LOT, ...) à étendre (sans abréviation)
- `Housenumber` avec number à NULL, mais sans postcode_id ! nécessaire pour mémoriser le bon CEA d'une voie multi-CP (voir issue #102 ), avec donc le lien sur le CP

**Comment by christopheprudent** [comment]
j'ai repris le traitement des écarts à partir du dump du 1/8
avec les totaux suivants:

 db  |     data     |  count
-----|--------------|----------
 BAN | Group        |  7529403
 RAN | Group        |  2240388
 BAN | Housenumber  | 26197611
 RAN | Housenumber  | 19429540
 BAN | Municipality |    36703
 RAN | Municipality |    36076
 BAN | Postcode     |    36883
 RAN | Postcode     |    36074


en voici un récapitulatif, avec delta=(+,!,-) pour (en plus, différent, en moins), par rapport à chaque(s) clé(s) des éléments d'adresse (Municipality, Postcode, Group, Housenumber). A noter que pour l'élément Voie, la clé de comparaison entre BAN et RAN est donc INSEE, libellé Voie normé (calculé à partir du libellé BAN), mais je n'ai pas alors obtenu la même qualité de libellé approchant, et je compte alors en écart des choses qui sont en fait OK dans la BAN, voir ci-dessous les variations OK : je ne sais pas si je suis bien clair :question: 

Il me reste aussi à vérifier le bien fondé du rapprochement IGN/POSTE (association CEA, matricule Voie)

 data     | delta |  count
--------------|-------|---------
 Group        | -     |   32328
 Group        | !     |     101
 Group        | +     |   79339
 Housenumber  | -     | 5755843
 Housenumber  | !     |   36178
 Housenumber  | +     | 7472044
 Municipality | -     |      53
 Municipality | !     |     568
 Municipality | +     |     785
 Postcode     | -     |     365
 Postcode     | +     |    1169

les données Voies sont à priori rapprochées seulement pour les départements 06, 33 et 90, 
avec en tout , 51 345 voies avec CEA, mais sans lien de code postal (voir précédent message)
et 15 944 750 numéros avec CEA

les données comparées sont disponibles sur un autre site GitHub : https://github.com/LaPosteSNA/check-init-of-BAN, dans le dossier ./data

en premières analyses, quelques soucis de rapprochement pour les voies sont dus à:
- chiffre écrit en tant que tel, et non en lettre (av du huit mai, ...)
rue du dix huit juin / rue du 18 juin

- variation d’orthographe
ex: chemin des launes (RAN), chemin des lones (BAN)

et d'autres par contre sont OK :+1:, malgré les variations d'écriture
- type de voie abrégé dans BAN et non dans RAN, style IMP pour Impasse, AV pour Avenue
(à noter que ce type de voie abrégé peut être positionné en milieu de libellé: 1e AV au lieu de 1e Avenue)

- libellé approchant, mais avec en plus 1 mot (espace, nom, article, ...)
ex: allée belle vue, au lieu de allée bellevue
ex: AVENUE GEN MARCEL PAROLDI (BAN) / AVENUE GENERAL PAROLDI (RAN)

- mot SAINT/SAINTE abrégé en ST/STE dans la BAN, alors que RAN n'effectue pas ces abréviations pour le libellé Voie

**Comment by christopheprudent** [comment]
analyse des écarts Group sur le dump du 24/8

 data     | delta |  count
:------------|-------|---------:
 Group        | -     |   621791
 Group        | !     |     493132
 Group        | +     |   5337613

pour cette nouvelle analyse, j'ai changé le mode de rapprochement entre la BAN et RAN : j'utilise ici la clé POSTE (group.laposte), qui correspond au matricule Voie
je pense en effet que cette approche sera celle qui nous permettra plus facilement de "valider" le contenu de la BAN, par rapport à notre propre référentiel (RAN)

- les cas en plus (pour rappel, présent dans BAN, absent dans RAN) font certainement référence aux "voies" de FANTOIR, 

- les cas en différence (même clé de rapprochement, au moins 1 attribut de différent)

- les cas en moins (absent dans BAN, présent dans RAN)

**Comment by odorie** [comment]
Au sujet des 600 000 groupes RAN non retrouvés dans la BAN, nous avons évoqué ce point lundi 29/08 lors de la réunion BAN team. Cet écart pourrait être présent dans les données IGN (export BDUNI/SGA) qui ont servi à l'initialisation de la BAN. Il pourrait aussi venir d'un bug lors de l'export IGN ou de l'init de la BAN. Il serait intéressant d'avoir plus d'informations sur le processus d'initialisation et le remplissage de la clé poste (cf ticket #164).
Sur le département 33, l'export IGN (fourni début juillet) comprend 55381 groupes (donc voies/lieux-dits). 44675 groupes ont un matricule voie.
@christopheprudent , je t'envoie ce fichier par mail pour pousser l'analyse. Pourras-tu en retour nous envoyer les voies du RAN sur ce département avec le matricule voie ?

**Comment by christopheprudent** [comment]
tu as cet export ci-dessus dans le lien du cas moins, voir commentaire : print_delta_group_minus_33.txt

**Comment by christopheprudent** [comment]
j'ai récupéré le fichier ban_group_33 IGN, et les voies manquantes BAN/RAN y sont bien présentes
le souci provient à priori du fait du codage FANTOIR _avec un dièse_
```
33048#004;péchot;;;00584402;LIEU DIT PECHOT;00584402;;;33048
33002#00C;bois majou;;;00580357;BOIS MAJOU;00580357;;;33002
33251#002;augine;;;;;;B009;B009;33251
33077#012;mouréou;;;00588861;LIEU DIT MOUREOU;00588861;;;33077
```

**Comment by odorie** [comment]
Un petit remarque : le premier champ est l'identifiant IGN. Il correspond souvent au fantoir.
Mais il y a pas mal de cas où ce champ comprend un # (par exemple quand la voie est créé dans la base IGN avant que l'on intègre le fantoir). La valeur n'a alors plus rien à voir avec le fantoir mais c'est un code propre IGN.
Pour avoir le code fantoir, il faut utiliser le 7 ème champ du fichier (id_fantoir) et pas l'identifiant IGN.

Quelques infos sur le premier cas mentionné (PECHOT):

IGN :
3 lieux-dits "pechot" dans les données IGN :
- 2 viennent de la DGFIP (péchot nord- péchot sud)
- 1 vient de La Poste (péchot ou lieu-dit pechot)

Les données ne sont pas appariées dans les données IGN (est-ce normal ?) d'où la présence de ces 3 lieux-dits : 2 DGFIP et 1 La Poste.

id_pseudo_fpb;nom;alias;type_d_adressage;id_poste;nom_afnor;id_postes;id_fantoir;id_fantoirs;code_insee
"33048B037";"pechot nord";"";"Classique";"";"";"";"B037";"B037";"33048"
"33048B036";"pechot sud";"";"Classique";"";"";"";"B036";"B036";"33048"
"33048#004";"péchot";"";"";"00584402";"LIEU DIT PECHOT";"00584402";"";"";"33048"

BAN :
Dans les données BAN, on ne retrouve que les 2 lieux-dits DGFIP 
pk,name,fantoir,laposte
2486358;"Pechot Nord";"33048B037";""
2486357;"Péchot Sud";"33048B036";""

Soit il manque dans la BAN un lieu-dit IGN/La Poste, soit il manque un lien d'appariement avec ce lieu-dit. 
Au vu des adresses liées et des coordonnées, je dirais qu'il manque un lien d'appariement (avec pechot sud ?) à la fois dans la BAN et les données IGN ??? 

Adresses liées :
IGN :
33048B037 -> une adresse le numéro 25
33048B036 -> 17 adresses (numéro "{"1 ","11 ","12 ","13 ","2 ","26 ","3 ","3 ","4 B","4 ","5 B","5001 ","5002 ","6 ","7 ","8 ","9 "}") 
33048#004 -> 13 adresses (numéro "{"1 ","11 ","12 ","13 ","2 ","3 ","4 BIS","4 ","5 ","6 ","7 ","8 ","9 "}")


BAN :
2486358 -> une adresse le numero 25
2486357 -> 17 adresses (numéro "{"1 ","11 ","12 ","13 ","2 ","26 ","3 ","4 B","4 ","5 BIS","5 B","5001 ","5002 ","6 ","7 ","8 ","9 "}")

**Comment by christopheprudent** [comment]
tu as raison, il semble que le lien manquant porte sur le libellé Péchot Sud, au vu des données Numéros de cette voie 
![numero_voie-584402](https://cloud.githubusercontent.com/assets/15735397/18194896/134753d8-70e9-11e6-9446-b46d306c54aa.PNG)

pas évident à automatiser, il faudrait alors tenir compte de cette liste de numéro, pour appairer 2 voies, de nom approchant, mais en différenciant alors le libellé retenu (BAN: Péchot Sud, LaPoste: Péchot)

**Comment by odorie** [comment]
Les autres cas mentionnés par @christopheprudent semblent similaires au cas de "PECHOT" :

------------------------------------------------------------------------------------
-------------------------- CAS 2 : BOIS MAJOU -------------------------------------------

IGN :
5 lieux-dits "bois majou" dans les données IGN :
- 3 viennent de la DGFIP (bois majou sud, bois-majou-nord, bois majou sud-est)
- 1 provient de la DGFIP et La Poste (grand bois majou nord)
- 1 vient de La Poste ("bois majou")

le "Bois Majou" de La Poste n'a pas été apparié avec les autres "bois majou sud " (...) dans les données IGN.

id_pseudo_fpb;nom;alias;type_d_adressage;id_poste;nom_afnor;id_postes;id_fantoir;id_fantoirs;code_insee
"33002B045";"bois majou sud";"";"";"";"";"";"B045";"B045";"33002"
"33002B044";"bois-majou-nord";"";"Classique";"";"";"";"B044";"B044";"33002"
"33002B042";"bois majou sud-est";"";"Classique";"";"";"";"B042";"B042";"33002"
"33002B106";"grand bois majou nord";"";"Linéaire";"00580361";"GRAND BOIS MAJOUNORD";"00580361";"B106";"B106";"33002"
"33002#00C";"bois majou";"";"";"00580357";"BOIS MAJOU";"00580357";"";"";"33002"

BAN :
Dans les données BAN, on ne retrouve que les 3 lieux-dits DGFIP seuls et le lieu-dit DGFIP/La Poste. Mais pas le lieu-dit, La Poste seul. 
pk,name,fantoir,laposte
2477333;"Bois Majou Sud-Est";"33002B045";""
2477330;"Bois Majou Sud-Est";"33002B042";""
2477332;"Bois-Majou-Nord";"33002B044";""
2477390;"Grand Bois Majou Nord";"33002B106";"00580361"

Il manque dans la BAN un lieu-dit IGN/La Poste ou un lien d'appariement ce lieu-dit.

------------------------------------------------------------------------------------
-------------------------- CAS 3 : AUGINE -------------------------------------------
Je ne retrouve pas ce cas dans le fichier RAN (dans https://github.com/LaPosteSNA/check-init-of-BAN/blob/master/data/print_delta_group_minus_33.txt)

IGN :
1 seul lieu-dit "augine" provenant uniquement de la DGFIP.

id_pseudo_fpb;nom;alias;type_d_adressage;id_poste;nom_afnor;id_postes;id_fantoir;id_fantoirs;code_insee
"33251#002";"augine";"";"";"";"";"";"B009";"B009";"33251"

BAN :
Dans les données BAN, on trouve 2 lieux-dits DGFIP :
 
pk,name,fantoir,laposte
2520507;"AUGINE-OUEST";"33251B009";""
2520504;"AUGINE-EST";"33251B008";""

------------------------------------------------------------------------------------
-------------------------- CAS 4 : MOUREOU -------------------------------------------

IGN :
5 lieux-dits "moureou" dans les données IGN :
- 4 viennent de la DGFIP (moureou-sud, moureou-ouest, moureou-est, lande de moureou)
- 1 vient de La Poste ("mouréou")

le "mouréou" de La Poste n'a pas été apparié avec les autres "mouréou " (...) dans les données IGN.

id_pseudo_fpb;nom;alias;type_d_adressage;id_poste;nom_afnor;id_postes;id_fantoir;id_fantoirs;code_insee
"33077B165";"moureou-sud";"";"Classique";"";"";"";"B165";"B165";"33077"
"33077B164";"moureou-ouest";"";"Classique";"";"";"";"B164";"B164";"33077"
"33077B163";"moureou-est";"";"Classique";"";"";"";"B163";"B163";"33077"
"33077B122";"lande de moureou";"";"Classique";"";"";"";"B122";"B122";"33077"
"33077#012";"mouréou";"";"";"00588861";"LIEU DIT MOUREOU";"00588861";"";"";"33077"

BAN :
Dans les données BAN, on trouve 5 lieux-dits DGFIP "moureou". Aucun La Poste
pk,name,fantoir,laposte
2493058;"Moureou-Sud";"33077B165";""
2493038;"Moureou-Sud";"33077B142";""
2493024;"Lande de Moureou";"33077B122";""
2493056;"Moureou-Est";"33077B163";""
2493057;"Moureou-Ouest";"33077B164";""

Il manque dans la BAN un lieu-dit IGN/La Poste ou un lien d'appariement sur ce lieu-dit.

**Comment by christopheprudent** [comment]
bilan BAN sur dump 20160824

 % VOIES avec ID_POSTE | % VOIES avec CEA_POSTE | % NUMEROS avec CEA_POSTE | % NUMEROS avec CP_POSTE
-----------------------|------------------------|--------------------------|-------------------------
                 21.50 |                  21.50 |                    60.67 |                   80.66

à noter que ce chiffrage des numéros exclut les données de Housenumber avec number à NULL

**Comment by christopheprudent** [comment]
voici les résultats de comparaison BAN/LaPOSTE sur le dump réduit (06-33) du 21/9

data|delta|count
:----|-----|-----:
Group|-|525
Group|!|25104
Group|+|50254
Housenumber|-|192100
Housenumber|!|2662
Housenumber|+|182394
Municipality|!|3
Municipality|+|2
Postcode|-|1
Postcode|+|7

**Comment by christopheprudent** [comment]
* avec écarts sur `Municipality`


db|insee|name|norme|delta
---|-----|----|-----|-----
BAN|06107|Roquestéron-Grasse|ROQUESTERON GRASSE|!
RAN|06107|LA ROQUE EN PROVENCE|LA ROQUE EN PROVENCE|!
BAN|33018|Aubie-et-Espessas|AUBIE ET ESPESSAS|!
RAN|33018|VAL DE VIRVEE|VAL DE VIRVEE|!
BAN|33371|Saint-Antoine|ST ANTOINE|+
BAN|33495|Salignac|SALIGNAC|+
BAN|33496|Sallebœuf|SALLEBEUF|!
RAN|33496|SALLEBOEUF|SALLEBOEUF|!


**remarque**: je me suis rendu compte en fait que les libellés avec OE sont en fait différents dans le référentiel LaPOSTE !

* avec écarts sur `Postcode`

db|insee|code|name|delta
---|-----|----|----|-----
BAN|06029|06150|CANNES|+
BAN|06004|06160|ANTIBES|+
BAN|06069|06520|GRASSE|+
BAN|33529|33115|LA TESTE DE BUCH|+
BAN|33154|33230|LES EGLISOTTES|+
RAN|33154|33230|LES EGLISOTTES ET CHALAURES|-
BAN|33495|33240|SALIGNAC|+
BAN|33371|33240|ST ANTOINE|+

**Comment by odorie** [comment]
Il faudrait découper ce ticket en plusieurs sous-tickets en indiquant les points à corriger/améliorer pour y voir plus clair.
Et indiquer ce qui acceptable ou non pour la mise en prod.

**Comment by odorie** [comment]
Des chiffres plus détaillés sur les écarts entre HN BAN et La Poste sont dans le ticket #175

**Comment by odorie** [comment]
Fermé au profit du ticket https://github.com/BaseAdresseNationale/donnees-initiales/issues/12
