### ISSUE TITLE
Demande de documentation sur le processus d'initialisation ban pour recette

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/api-gestion#164]
Dans le cadre de la recette du contenu initial de la BAN, nous avons prévu de valider le processus d'initialisation notamment à partir de la description des différentes étapes de cette initialisation.
Pour réaliser cette recette, nous aurions besoin d'une petite documentation de cette initialisation contenant en particulier : 
- ordre de chargement des données
- appariements réalisés à chaque étape
- traitement des appariements : que devient une donnée appariée, que devient une donnée non appariée.
- remplissage des différents attributs ban à partir des attributs d'origine

Par exemple une voie IGN est-elle créé si elle n'est pas déjà présente dans les données DGFIP/BANO. Même question pour les adresses. Quand une adresse IGN est-elle écrasée par une autre donnée ? Comment sont traités les doublons présents dans les données IGN ?

**Comment by yohanboniface** [comment]
Pour l'ordre de chargement des données, c'est tout simplement celui des fichiers (1_xxx, 2_xxx).
Tu as un lien vers le répertoire avec les données? Si c'est pas le cas, envoie-nous un email :)

Ensuite, c'est ce script qui est utilisé: https://github.com/BaseAdresseNationale/ban/blob/master/ban/commands/init.py (les tests qui vont avec https://github.com/BaseAdresseNationale/ban/blob/master/ban/tests/commands/test_init.py).
Example de ligne de commande pour lancer l'import:

    ban import:init data/*.json

En partant du principe que tous les fichiers (bien nommés) sont dans `data/`.

Le fonctionnement du script est assez trivial:
- il prend les fichiers dans l'ordre qu'on lui donne
- pour chaque entrée d'un fichier:
  - si l'entrée existe déjà avec la même source, elle n'est pas réimportée
  - si l'entrée n'existe pas, elle est créée
  - si l'entrée existe, mais avec un source différente, une nouvelle version est créée
- si l'entrée est importée (création ou mise à jour), toutes les données présentes sont considérées (c'est le script de @cquest qui décide ce qui est ou pas dans le fichier)
- selon les étapes, l'appariement se fait via: INSEE, FANTOIR, CIA

Pour ce qui est de la génération des fichiers de données, il faut voir avec le sieur @cquest :)

**Comment by cquest** [comment]
Voici une liste des étapes:

- 01 municipality depuis COG
- 02 groups depuis FANTOIR
- 03 postcode depuis fichier officiel des codes postaux
- 04 housenumber depuis DGFiP/BANO
- 05 position depuis DGFiP/BANO
- 06a housenumbers BAN qui ont un fant_voie et pas de fant_ld
- 06b housenumbers BAN qui ont un fant_ld et pas de fant_voie
- 07a positions BAN qui ont un fant_voie et pas de fant_ld
- 07b positions BAN qui ont un fant_ld et pas de fant_voie
- 08 housenumbers IGN absents du cadastre
- 09a rapprochements IGN/DGFiP
- 09b positions IGN pour les housenumbers absents du cadastre
- 10 group:  La Poste: mise à jour du matricule à partir du lien SGA
- 11 housenumber: création du CEA pour le group
- 12 housenumber ajout du CEA
- 13 housenumbers AITF
- 14 positions AITF
- 15 group: noms complets DGFiP/BANO
- 16 group: noms recapitaliés de la BAN par les scripts de sortie ODbL de la BAN

Chaque étape génère un fichier json importé ensuite en ligne de commande par le code d'import.

**Comment by odorie** [comment]
Merci pour cette description.
Quelques petites questions/remarques (qui font aussi suite à la recette en cours) :
- nous ne trouvons pas d'étapes correspondants à l'import des voies/lieux-dits IGN : ceci permettrait de rapprocher les voies IGN des voies déjà chargées dans la BAN (ajout de l'identifiant IGN des voies) et d'ajouter dans la BAN les voies IGN/la Poste sans code fantoir (dans la base IGN) (par exemple les voies venant du guichet adresse) . La clé de rapprochement serait le code fantoir (et pas l'id_pseudo_fpb). On pourrait compléter si besoin par un rapprochement avec les noms.
-  Pour les étapes 06a, 06b, 07a et 07b, ne faudrait-il pas remplacer l'export BAN (v0-guichet) par l'export IGN (SGA-BDUni) : plus complet et amélioré.
- Que signifie  l'étape "08 housenumbers IGN absents du cadastre" : s'agit-il de l'ajout dans la BAN des housenumbers IGN absents de la BAN.
- Que signifie l'étape "09a rapprochements IGN/DGFiP" ?
- Que signifie  l'étape "09b positions IGN pour les housenumbers absents du cadastre" : s'agit-il de l'ajout dans la BAN des positions IGN pour les hn venant de l'étape 8.

**Comment by cquest** [comment]
1. effectivement, c'est une étape (importante) qui manque, elle sera présente dans le prochain dump. Il y a une phase de rapprochement simple qui a été ajoutée, pour compléter les id_fantoir assez évidents. id_fantoir est utilisé si présent, puis on passe _ id_pseudo_fbp. L'objectif est de tout avoir tout en limitant la création de doublons.
2. les étapes 06/07 pourront même être supprimées. Je les avais ajouter pour avoir des données ailleurs que sur les 3 départements tests initiaux. Ce n'est plus trop d'actualité.
3. Non, ce sont les housenumber IGN absent des données DGFiP du cadastre extraites par BANO (04 et 05)
4. 09a: ce sont les positions IGN/SGA qui sont ajoutées là où on avait déjà une position DGFiP/BANO
5. Oui, c'est ça, position pour les housenumbers ajoutés par l'étape 08

Pour l'init partielle en cours, il y a plus d'étapes... dès que j'ai fait le tour je remet ça à jour.

**Comment by cquest** [comment]
Les scripts de préparation des données sont maintenant sur github:
https://github.com/BaseAdresseNationale/ban/tree/master/scripts/init

**Comment by odorie** [comment]
Je ferme ce ticket car la description de la méthode a été fournie.
