### ISSUE TITLE
écarts BAN/IGN sur init

### ISSUE THREAD

**Issue by ebuard** [BaseAdresseNationale/api-gestion#165]
Concernant la qualification de la base initialisée, il nous manque le type d'adressage sur les Group. Y a t'il également des attributs de source sur chaque table?

Sur les écarts quantifiés entre BDuni et BAN, comme ce travail prend du temps et donc des ressources (de collecteurs), nous le ferons qu'à la dernière initialisation de la BAN (vers mi-août donc).

_Ex-nihilo_, on peut noter quelques points:
-  je n'ai pas noté de problème d'abbréviations, de cohérence entre objets
- il semble que la table de version fait 98,5% du volume total (100Go), sans même avoir fait des modifs de version. Peut-on optimiser cette table? 
- la fusion de communes ne semble pas avoir été faite
- il n'y pas de liens hiérarchiques de positions

Nous attendons la seconde livraison.
Elodie

**Comment by odorie** [comment]
je ferme ce ticket, car plus à jour ou repris dans d'autres tickets plus détaillés
