### ISSUE TITLE
écarts BAN/LaPOSTE sur init (Housenumber)

### ISSUE THREAD

**Issue by christopheprudent** [BaseAdresseNationale/api-gestion#175]
analyse des écarts Housenumber sur le dump du 24/8

| data | delta | count |
| :-- | --- | --: |
| Housenumber | - | 5362898 |
| Housenumber | ! | 47317 |
| Housenumber | + | 7064747 |

pour cette nouvelle analyse, j'ai changé le mode de rapprochement entre la BAN et RAN : j'utilise ici la clé POSTE (housenumber.laposte), qui correspond au CEA (clé présente dans le fichier HEXACLE)
je pense en effet que cette approche sera celle qui nous permettra plus facilement de "valider" le contenu de la BAN, par rapport à notre propre référentiel (RAN)

avec

| data | attributs |
| :-- | :-- |
| Housenumber | code, id, number, ordinal |
- les cas en plus (pour rappel, présent dans BAN, absent dans RAN) 
- les cas en différence (même clé de rapprochement, au moins 1 attribut de différent)
  liste complète dispo sous https://github.com/LaPosteSNA/check-init-of-BAN/blob/master/data/print_delta_housenumber_diff.txt
  souvent lié à l'erreur de rapprochement avec la voie (id différent)
- les cas en moins (absent dans BAN, présent dans RAN)

**Comment by odorie** [comment]
Fermé au profit de #154
