### ISSUE TITLE
Mauvais remplissage de kind et positioning sur les positions provenant de l'IGN lors de l'initialisation de la BAN

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/api-gestion#179]
La plupart des positions provenant de l'IGN ont leur champ "kind" valant "unknow" et leur champ "positioning" valant "other".

Nous avions proposé à la réunion sur l'initialisation à Libourne (dans le doc associé) un remplissage à partir de l'export SGA/BDUni de l'IGN, (plus précisément des fichiers ban.house_number<dep>.csv et des champs  type_de_localisation, indice_de_positionnement, designation_de_l_entree) : 

<table>
   <tr>
       <td>Champs IGN (ban.housenumber<dep>.csv)</td>
       <td>Position ban</td>
   </tr>
   <tr>
       <td>indice_de_positionnement = 6</td>
       <td>Pas de position</td>
   </tr>
   <tr>
       <td>indice_de_positionnement = 5</td>
       <td> Kind « Address area », Positioning « unknow»</td>
   </tr>
   <tr>
       <td>type de localisation = « A la plaque»</td>
       <td>Kind « Entrance », Positioning « unknow»</td>
   </tr>
   <tr>
       <td>type de localisation = « Projeté du centre parcelle»</td>
       <td>Kind « Segment », Positioning « projection »</td>
   </tr>
   <tr>
       <td>type de localisation = « Au complément d’adressage»</td>
       <td>Kind “building” si designation_d_l_entree contient “BATIMENT ou ENTRÉE ou CAGE” 
Autrement Kind « Entrance » 
Positionning « unknow»</td>
   </tr>
   <tr>
       <td>type de localisation = « Interpolée»</td>
       <td>Kind «Segment», Positionning « interpolation »</td>
   </tr>
   <tr>
       <td>type de localisation = « A la zone d’adressage»</td>
       <td>Kind «Address area», Positionning « unknow»</td>
   </tr>
   <tr>
       <td>type de localisation = « Au centre commune»</td>
       <td>Pas de position</td>
   </tr>
</table>

**Comment by cquest** [comment]
positionning "other" est semble-t-il ajouté par le code d'import, ce n'est pas dans les json que je prépare...

pour position "unknown", en fait je ne l'ai pas renseigné (si pas renseigné c'est que c'est inconnu sinon ça serait renseigné)

**Comment by cquest** [comment]
Réglé en grande partie avec l'init du 21-09-2016, à vérifier en recette.

**Comment by odorie** [comment]
Une partie des soucis signalés lors de l'init du 24/08 a été réglée. Cependant il en reste encore quelques-uns. Leur description ci-dessous :

- le champ "positioning" vaut toujours other

- il manque le kind "Adress Area" pour basculer les indices de positionnement 5 ou les types de localisation IGN "A la zone d'adressage". Cette valeur est une valeur "INSPIRE" et nous permettrait de conserver et caractériser les adresses IGN placées "grossièrement" dans un lieu-dit

- Environ 16 000 adresses IGN d'indice de positionnement 5 sont transférées dans la BAN avec un kind unkown --> Il faudrait les basculer en kind Address Area

- Environ 16 000 adresses IGN de type de localisation "A la zone d'adressage" sont basculées  avec un kind unkown --> Il faudrait les basculer en kind Address Area

- Environ 46 000 adresses IGN d'indice de positionnement 6 sont basculées  avec un kind unkown --> Il ne faudrait pas créer de position pour ces adresses IGN

- Environ 3000 adresses IGN de type de localisation "Au centre commune" sont basculées  avec un kind unkown --> Il ne faudrait pas créer de position pour ces adresses IGN

- Environ 16 000 adresses IGN de type de localisation "A la plaque" d'indice de positionnement différents de 5 et 6 sont basculées à kind "Unknown" --> Il faudrait les basculer à kind 'entrance'. Quelques exemples d'identifiants ign concernés avec les fantoirs: 
ADRNIVX_0000000261393212 | 061200248
 ADRNIVX_0000000261393215 | 061200248
 ADRNIVX_0000000261393217 | 061200248
 ADRNIVX_0000000261393220 | 061200248

- Environ 6 500 adresses IGN de type de localisation "Interpolée" d'indice de positionnement différents de 5 et 6 sont basculées à kind "Unknown" --> Il faudrait les basculer à kind 'segment'. Quelques exemples d'identifiants ign concernés avec les fantoirs: 
 ADRNIVX_0000000261413098 | 060160020
 ADRNIVX_0000000261413099 | 060160020
 ADRNIVX_0000000261413102 | 060160020
 ADRNIVX_0000000261413104 | 060160020
 ADRNIVX_0000000261413105 | 060160020

**Comment by odorie** [comment]
Depuis l'init du 30/06/2017, le champ kind de Position est correctement rempli. Reste le souci du champ positioning. J'ouvre un ticket spécifique dans le dépôt d'init https://github.com/BaseAdresseNationale/donnees-initiales/issues
