### ISSUE TITLE
gestion du problème de millésimage

### ISSUE THREAD

**Issue by ebuard** [BaseAdresseNationale/api-gestion#182]
_Pour mémoire:_
Les fusions de communes 2016 n’ont pas été chargées dans la BAN, alors qu’elles le sont dans les données IGN et La Poste utilisées en comparaison. En conséquence, la recette de la BAN détecte de nombreuses anomalies. Il faut donc charger le COG 2016. 
Deux actions sont nécessaires : obtenir le chaînage des codes Fantoir auprès de la DGFiP en cas de fusion de communes et disposer d’un outil pour fusionner directement les communes dans la BAN pour conserver le lien sur les communes fusionnées.

**Comment by cquest** [comment]
Pour le chaînage FANTOIR, j'ai généré une liste de mise à jour des codes FANTOIR à partir de l'édition d'août 2016 en comparant les dates d'annulation sur l'ancienne commune et de création sur la nouvelle ainsi que le début des libellés.
Voici la requête:
```
SELECT f2015.fantoir2 as fantoir_2015,  string_agg(f2016.fantoir2,',') as fantoir_2016, f2015.nature_voie ||' '||f2015.libelle_voie, string_agg(f2016.nature_voie ||' '||f2016.libelle_voie,',')  AS nom_2015
FROM dgfip_fantoir201607 f2015
JOIN fusions f ON (f.oldinsee=f2015.code_insee)
LEFT JOIN dgfip_fantoir201607 f2016 ON (f2016.code_insee=f.insee AND f2015.date_annul>'2015' AND f2015.nature_voie=f2016.nature_voie AND f2016.libelle_voie like f2015.libelle_voie ||'%' AND f2015.fantoir!=f2016.fantoir AND f2015.ld_bati=f2016.ld_bati AND f2015.date_annul<=f2016.date_creation)
WHERE f2015.date_annul>'2015000' AND f2016.fantoir2 IS NOT NULL
group by 1,3 having count(*)=1
ORDER BY 1;
```

Voici les fichiers CSV correspondants:
[fusion_fantoir.zip](https://github.com/BaseAdresseNationale/ban/files/515649/fusion_fantoir.zip)
[fusion_fantoir_bad.zip](https://github.com/BaseAdresseNationale/ban/files/515650/fusion_fantoir_bad.zip)

Le fichier "bad" contient 707 codes FANTOIR annulés pour lesquels il n'y a soit pas de correspondance sur la commune nouvelle soit il y en a plusieurs.

**Comment by odorie** [comment]
Idem pour l'intégration du COG 2017

**Comment by odorie** [comment]
Déplacé vers le dépôt d'init https://github.com/BaseAdresseNationale/donnees-initiales/issues
