### ISSUE TITLE
SIREN vide sur les municipalities à l'issue de l'initialisation de la ban

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/api-gestion#187]
Pourquoi ne pas remplir ce champ à l'initialisation ?

**Comment by cquest** [comment]
Le SIREN avait surtout été envisagé pour gérer éventuellement les droits des EPCI (ils n'ont pas de code INSEE comme les commune, mais un EPCI).
Comme la gestion des droits n'est pas faite directement par l'API, j'ai zappé cette étape.

Je peux rajouter cette étape bien que sans conséquence pour le reste de l'init (et donc pas très prioritaire).

**Comment by odorie** [comment]
Déplacé vers le dépôt d'init
