### ISSUE TITLE
Municipality split

### ISSUE THREAD

**Issue by yohanboniface** [BaseAdresseNationale/api-gestion#19]
Sometimes, a municipality split in two municipalities. We need to handle that with a command line.

**Comment by yohanboniface** [comment]
Closed in favor of #62

**Comment by yohanboniface** [comment]
Confused with #18

**Comment by ebuard** [comment]
A notre connaissance, il y a peu de scission de communes en ce moment (moins d'une par an).
Autant pour la fusion de communes, un   outil automatique a été développé, pour la scission, cela semble difficile à moins d'avoir la géométrie des communes résultant de la scission et toutes les positions de hn.

**Comment by jdesboeufs** [comment]
On a les géométries car souvent les scissions sont des retours à une situation précédente.
C'est vraiment pas prioritaire, on pourra le faire à la main les 2/3 premières années ;)
