### ISSUE TITLE
Homogénisation des noms des groupes lors de l'initialisation de la ban

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/api-gestion#190]
A l'issue de l'initialisation de la ban, les noms des groupes (environ 7,5 millions) sont en majorité en majuscules non accentuées (5.4 millions). Le reste est en minuscule accentués (ou non) (avec première lettre en majuscule). Il reste aussi des abréviations (0.2 million).

Faut-il améliorer l'initialisation en homogénéisant ces noms ? Par exemple passer tout en minuscules accentuées désagrégées (avec première lettre en majuscule).

**Comment by cquest** [comment]
Ce sont essentiellement les lieux-dits qui sont encore en majuscule, car je nous n'avons pas à ma connaissance de source fiable pour les remettre en minuscules accentuées.

Pour les libellés en général nous sommes partis sur le principe d'aller vers le plus détaillé:
- majuscules abbrégées
- majuscules non abrégées
- minuscules accentuées non abrégées
- minuscules accentuées et capitalisées non abrégées

Les transformations automatiques sont malheureusement parfois un peu alléatoires et à éviter si possible.
Du coup, on n'a pas en base d'homogénéité, mais la base reflette l'état de notre connaissance... chacun est libre d'homogénéiser comme il le souhaite dans ses usages.

**Comment by odorie** [comment]
Vaut-il mieux avoir : 
- une base homogène avec des approximations de passage en minuscules accentuées et de dés-abréviations qui seront corrigées au fil du temps 
- Ou une base hétérogène (qui sera aussi améliorée au fil du temps), avec éventuellement plus de difficultés à traiter côté utilisateur ? Notamment les 200 000 abréviations.

Proposition : demander l'avis aux utilisateurs.

PS : dans la base, des données ont déjà été basculées en minuscules accentuées de façon automatique (certaines données provenant de l'IGN).

**Comment by cquest** [comment]
Je pense que l'on peut homogénéiser lors des exports pour diffusion en fonction d'ailleurs des usages attendus.

Je ne suis pas partisan de conserver les minuscules qui ont été accentuées automatiquement, ou alors de le refaire mais avec une base de mot locale à chaque commune et pas unique (et nationale).

On gros chantier de remise à niveau des libellés sera sûrement nécessaire mais avec les communes dans la boucle pour garantir qu'on est au plus proche des noms qu'elle a choisit.

Pour les abréviations, il y a un sujet aussi de ce côté car certaines désabréviations ont pu introduire des erreurs (cas de 'EN' devenue 'enceinte').

**Comment by odorie** [comment]
Lors de la réunion Ban Team, nous avons évoqué la possibilité de traiter les cas sûrs, notamment les désabréviations.
Actuellement sur le dump du 21/09, un petit comptage des abréviations présentes (sur environ 126 000 groupes) : 

```
abréviation	| nombre
PL				| 1159
RES				| 930
RTE				| 790
AV				| 653
SQ				| 217
CHEM			| 184
BD				| 136 (en début de nom)
RPT				| 106
SEN				| 62

```

Lors de la réunion Ban team, il a aussi été proposé d'ajouter un champ normalisé en sortie de l'API

**Comment by cquest** [comment]
Ok pour appliquer les désabréviations non ambiguës

**Comment by odorie** [comment]
Déplacé vers https://github.com/BaseAdresseNationale/donnees-initiales/issues/4
