### ISSUE TITLE
Noms des groupes "non conformes" à l'issue de l'initialisation de la ban

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/api-gestion#191]
A l'issue de l'initialisation de la ban, on observe 3 types d'anomalies dans les noms des groupes :
1. noms avec que chiffres (407 cas). Exemple :
   
   fantoir  |            name
   -----------+----------------------------
   09085B040 | 067
   09214B245 | 004
   11065B054 | 021
   11129B136 | 077
   ...
2. noms avec une apostrophe suivi d'un blanc (381 cas). Exemple :
   
   fantoir  |               name
   -----------+-----------------------------------
   010850018 | RTE DU CHATEAU D' EAU
   010850010 | RTE DE L' ANCIEN LAVOIR
   011330100 | Rue de l'' École
   011330090 | Route de l'' Ecoincon
   011330110 | Rue de l'' Église
   011660060 | CHE D ' ARS
   ...
3. noms avec des "/" (2 noms séparés) (956 cas). Exemple : 
   
   fantoir  |                                                       name
   -----------+------------------------------------------------------------------------------------------------------------------
   01053X023 | PKG TEYNIERE/PREFECTURE
   012910150 | CHE PERREX A ST GENIS/MENTHON
   012910140 | CHE PERREX A ST CYR/MENTHON
   022900059 | Chemin Dep Montcourt /Montbonneil
   ...

**Comment by cquest** [comment]
Cas 1: ce sont des données provenant de FANTOIR. Elles sont sûrement invalides... à remonter vers la DGFiP pour voir l'intérêt de les conserver.

Cas 2: corrigé https://github.com/BaseAdresseNationale/ban/commit/cf383768f2f4eb5cce29ce768a64923e43fe1b98

Cas 3: doit-on les remplacer ? si oui par quoi les remplacer ? une suggestion ?

**Comment by odorie** [comment]
Référencé dans le dépôt sur l'init https://github.com/BaseAdresseNationale/donnees-initiales/issues
