### ISSUE TITLE
Non chargement de voies/lieux-dits IGN (ou non mise en place de lien d'appariement) lors de l'initialisation ban

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/api-gestion#192]
A l'issue de l'initialisation ban, de nombreuses voies/lieux-dits IGN ne sont pas retrouvés dans la BAN (cf ticket #154). L'ordre de grandeur n'est pour l'instant pas quantifié car l'identifiant ign n'a pas été chargé sur les groupes (cf ticket #178). Il pourrait être de l'ordre de plusieurs centaines de milliers comme pour les écarts BAN/La Poste. Nous allons chercher à le quantifier plus finement.

Pour être plus précis, ces voies IGN, soit n'existent pas dans la BAN, soit sont bien là mais n'ont pas d'identifiant IGN ou La poste (appariement non mis en place entre BAN/IGN/La Poste) dans la BAN. Les adresses IGN sur ces voies manquantes doivent alors aussi manquer ou ne pas voir d'identifiant IGN dans la BAN. Ce dernier point est à vérifier.

Un piste évoquée dans les tickets #178 et #154 serait que, lors de l'initialisation ban avec les fichiers csv IGN, le rapprochement entre voies IGN et voies BAN ait été fait avec le champ id_pseudo_fpb et non avec le champ id_fantoir.

Au delà de ce souci de chargement du fichier csv IGN, se pose la question du non chargement des voies IGN n'ayant pas de fantoir (donc des voies que l'IGN n'a pas rapproché des données de la DGFIP). Actuellement il me semble que ces données ne sont pas chargées dans la BAN mais du coup, on va vraiment perdre des voies/lieux-dits IGN et La Poste (et donc des adresses). Il est par ailleurs troublant que tous les groupes ban aient un code fantoir. Pour des voies provenant uniquement de La Poste ou IGN, au final, dans la BAN, ne devrait-on pas trouver des groupes sans fantoir ?

A discuter en réunion BAN Team, mais nous pensons qu'il faudrait charger toutes les voies IGN ou La Poste pour ne rien perdre. Il y aura des doublons dans la BAN mais ils seront éliminés au fil du temps.

**Comment by cquest** [comment]
Je confirme qu'il y a un gros trou à combler.
Il me semble important d'essayer de rapprocher et dédoublonner le plus possible avant ou pendant l'initialisation car j'ai peur que sinon on traine ces doublons pendant bien longtemps.
Il y a un peu plus de 300000 groupes à rapprocher.
Une première passe permet de rapprocher facilement 25% (voir https://github.com/BaseAdresseNationale/ban/issues/178).

**Comment by odorie** [comment]
Sur l'init du 21/09, c'est beaucoup mieux : sur les 72 817 groupes ign, on en retrouve 72 183 si l'on se réfère aux identifiants IGN.

Il n'en manque plus que 634 soit moins de 1 % (sur l'init du 24/08, on était plutôt sur du 10 %).

Je suis en train de faire un sondage sur les 634 pertes pour essayer de comprendre ce qu'il se passe...

**Comment by odorie** [comment]
Retour sur les 634 voies IGN manquantes si l'on se réfère aux identifiants IGN.
Lors de l'init ban, des appariements sont mis en place et les voies IGN fusionnées ou supprimées. Cette action explique les voies IGN non retrouvées.
Conséquence supplémentaires : des housenumbers IGN sont fusionnés et les doublons de numéro-ordinal supprimés. 
Donc résoudre ce ticket résoudrait aussi en partie le ticket #193.
Après un sondage sur les 634 voies : une partie de ces fusions semble justifiée (cf ex 1 et 2). D'autres cas posent questions (cf ex 3).
Par ailleurs, une action de correction (fusion, appariement de voies) est envisagée dans le SGA (contrôle en cours côté IGN) (cf #218).

Quelques exemples : 

- **ex1** :  
2 voies IGN "les genêts" (id 060041380) et "allée des genêts" (id 06004#0AI)
Une voie BAN "Allée des Genêts"    (fantoir 060041380 )

- **ex2** :  
2 voies IGN "AV DE L ORANGERIE" (id 06004#08T, pas de fantoir) et "avenue des orangers " (id 060042357, pas de fantoir)
Dans les données IGN, Il manque donc un code fantoir. De plus celui de "AV DE L ORANGERIE" est en fait celui  "avenue des orangers ".

Dans la BAN, les 2 voies sont correctes mais une des 2 voies n'a pas d'identifiant IGN.    

- **ex3** :
2 voies IGN : "LIEU-DIT BAUDRIT EST" (id = 33317#00G) pas de fantoir, avec 17 adresses
et "RUE SOUS LE BARRI" (id = 33317B005 ) fantoir 33317B005 avec 15 adresses.

Dans la BAN, on a une seule voie "BAUDRIT EST" fantoir 33317B005  avec 32 adresses.
Cette fusion est-elle justifiée ?

**Comment by odorie** [comment]
Réglé lors de l'init du 30/06/2017
