### ISSUE TITLE
1/4 des house numbers n'ont pas de code postaux suite à l'initialisation ban

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/api-gestion#196]
Suite à l'initialisation ban, environ 24 % de house numbers ne pointent pas vers un code postal.

Ce chiffre nous semble élevé ? 

Dans les exports ign (csv SGA/BDUNI du 10 juillet), le code postal est quasiment toujours rempli.

**Comment by cquest** [comment]
C'est la conséquence de https://github.com/BaseAdresseNationale/ban/issues/178

A revoir sur le prochain dump.

**Comment by cquest** [comment]
En principe corrigé... à vérifier en recette (je passe le relais)

**Comment by cquest** [comment]
Attention, pour la recette côté IGN, certains codes postaux issus du SGA ne correspondent par aux données RAN.
J'ai donc mis à jour ces codes postaux (étape 12c) pour être conforme au RAN vu que la source d'autorité pour le CP est La Poste.

**Comment by odorie** [comment]
Fermé au profit du #211
