### ISSUE TITLE
Doublons potentiels de house number BIS vs B, TER vs T suite à l'initialisation BAN

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/api-gestion#197]
Suite à l'initialisation BAN, on trouve dans les données environ 220 000 Housenumber BIS qui sont aussi en B, environ 32 000 TER qui sont aussi en  T.

Il est probable qu'il s'agisse de doublons,  provenant de 2 sources différentes : codés dans une base source en "BIS" et dans une autre base source en "B".

Je me renseigne en interne IGN pour voir s'il n'y a pas un souci de codage connu des BIS -> B.

Quelques exemples : 

**Exemple 1** : Voie de fantoir 010040420 (pk = 331)
number | ordinal |           ign            | parent_id |            attributes
--------+---------+--------------------------+-----------+----------------------------------
 109    | B       | ADRNIVX_0000000348711163 |       331 | "source"=>"IGN (2016-06)"
 109    | BIS     |                          |       331 | "source"=>"DGFiP/BANO (2016-04)"
 11     | B       | ADRNIVX_0000000307421722 |       331 | "source"=>"IGN (2016-06)"
 11     | BIS     | ADRNIVX_0000000285713613 |       331 | "source"=>"IGN/Poste (2016-06)"
 16     | B       | ADRNIVX_0000000285713617 |       331 | "source"=>"IGN (2016-06)"
 16     | BIS     |                          |       331 | "source"=>"DGFiP/BANO (2016-04)"
 24     | B       | ADRNIVX_0000000329142735 |       331 | "source"=>"IGN (2016-06)"
 24     | BIS     |                          |       331 | "source"=>"DGFiP/BANO (2016-04)"
 33     | B       | ADRNIVX_0000000285711239 |       331 | "source"=>"IGN (2016-06)"
 33     | BIS     |                          |       331 | "source"=>"DGFiP/BANO (2016-04)"
 36     | B       | ADRNIVX_0000000285711243 |       331 | "source"=>"IGN (2016-06)"
 36     | BIS     |                          |       331 | "source"=>"DGFiP/BANO (2016-04)"
 38     | B       |                          |       331 | "source"=>"DGFiP/BANO (2016-04)"
 38     | BIS     | ADRNIVX_0000000348711130 |       331 | "source"=>"IGN/Poste (2016-06)"
 70     | B       | ADRNIVX_0000000285711157 |       331 | "source"=>"IGN (2016-06)"
 70     | BIS     |                          |       331 | "source"=>"DGFiP/BANO (2016-04)"
 76     | B       | ADRNIVX_0000000285711164 |       331 | "source"=>"IGN (2016-06)"
 76     | BIS     |                          |       331 | "source"=>"DGFiP/BANO (2016-04)"

**Exemple 2** : Voie de fantoir 010040610 (pk = 403)
number | ordinal |           ign            | parent_id |            attributes
--------+---------+--------------------------+-----------+----------------------------------
 106    | B       | ADRNIVX_0000000285716596 |       403 | "source"=>"IGN (2016-06)"
 106    | BIS     |                          |       403 | "source"=>"DGFiP/BANO (2016-04)"
 111    | B       | ADRNIVX_0000000285716602 |       403 | "source"=>"IGN (2016-06)"
 111    | BIS     |                          |       403 | "source"=>"DGFiP/BANO (2016-04)"
 118    | B       | ADRNIVX_0000000285716611 |       403 | "source"=>"IGN (2016-06)"
 118    | BIS     |                          |       403 | "source"=>"DGFiP/BANO (2016-04)"
 131    | B       | ADRNIVX_0000000285716619 |       403 | "source"=>"IGN/Poste (2016-06)"
 131    | BIS     |                          |       403 | "source"=>"DGFiP/BANO (2016-04)"
 133    | B       | ADRNIVX_0000000285716621 |       403 | "source"=>"IGN/Poste (2016-06)"
 133    | BIS     |                          |       403 | "source"=>"DGFiP/BANO (2016-04)"
 181    | B       | ADRNIVX_0000000285711903 |       403 | "source"=>"IGN (2016-06)"
 181    | BIS     | ADRNIVX_0000000285711902 |       403 | "source"=>"IGN/Poste (2016-06)"
 187    | B       | ADRNIVX_0000000348711177 |       403 | "source"=>"IGN (2016-06)"
 187    | BIS     |                          |       403 | "source"=>"DGFiP/BANO (2016-04)"
 25     | B       | ADRNIVX_0000000325673806 |       403 | "source"=>"IGN/Poste (2016-06)"
 25     | BIS     |                          |       403 | "source"=>"DGFiP/BANO (2016-04)"
 28     | B       | ADRNIVX_0000000285716849 |       403 | "source"=>"IGN (2016-06)"
 28     | BIS     |                          |       403 | "source"=>"DGFiP/BANO (2016-04)"
 65     | B       | ADRNIVX_0000000285716879 |       403 | "source"=>"IGN (2016-06)"
 65     | BIS     |                          |       403 | "source"=>"DGFiP/BANO (2016-04)"

**Comment by christopheprudent** [comment]
j'ai vérifié côté POSTE,

- exemple 1: 
numéros avec extension BIS (11, 22, 34, 38, 52, 54, 56, 68, 69, 107)
numéros avec extension TER (56)

- exemple 2:
numéros avec extension BIS (2, 4, 8, 19, 61, 63, 65, 106, 108, 111, 113, 115, 124, 129, 181, 187)

**Comment by odorie** [comment]
Après enquête auprès de la production IGN, l'indice de répétition "B" dans l'export IGN peut soit représenter vraiment un "B" sur le terrain soit un "BIS".

Du coup, ces doublons observés dans la BAN viennent vraisemblablement des données IGN.

Est-il possible de revoir l'initialisation BAN de la façon suivante : 
- si , avant l'import des données IGN ,  on a dans la BAN un numéro donné xx, pour lequel il y a un BIS seulement et pas de "B" 
- et si ,dans les données IGN, pour ce même numéro xx, il y a un B et pas de BIS
- alors lors de l'import des données IGN dans la BAN, considérer le B comme un BIS (récupérer l'identifiant IGN et la géométrie).

Il faudra aussi que l'IGN corrige ses données, pour les faire converger vers la BAN, mais cela va prendre un peu de temps ...

**Comment by cquest** [comment]
C'est un problème signalé de longue date... mais ça va être un peu plus compliqué car dans les données IGN, on trouve aussi les 2 pour une même adresse (B et BIS alors qu'il n'y a que BIS sur le terrain: cas du 181 dans le 2ème exemple ci-dessus).

Dans ce cas, que fait-on de la seconde ?

Une solution consiste à importer les deux, puis à refaire un passage par la suite pour supprimer le doublon et créer la redirection B > BIS tout en se méfiant de l'existence de B + BIS sur le terrain.

Pour info, les données DGFiP/BANO regénèrent le BIS/TER en vérifiant qu'il n'y a pas d'autres lettres que les classiques B/T/C/Q.

**Comment by cquest** [comment]
Je n'ai pas pu traiter ce point sur l'init du 21-09-2016... à ajouter pour la prochaine itération.

**Comment by odorie** [comment]
Réouvert et précisé dans le dépôt d'initialisation https://github.com/BaseAdresseNationale/donnees-initiales/issues
