### ISSUE TITLE
doublons potentiels sur les groups

### ISSUE THREAD

**Issue by christopheprudent** [BaseAdresseNationale/api-gestion#199]
voici une liste d'~125 000 voies en doublon, parfois avec la même source
liste complète disponible sous https://github.com/LaPosteSNA/check-init-of-BAN/blob/master/data/print_duplicate_group.txt

à noter que pour 1 même libellé de Voie, le type (way/area) peut être différent

ex:

| insee | pk | id | version | created_at | created_by_id | modified_at | modified_by_id | attributes | name | alias | kind | addressing | fantoir | laposte | ign | municipality_id |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 01084 | 14262 | ban-group-2b0d7a4823054399a6daae0d1345d882 | 2 | 2016-07-20 09:26:06.412323 | 9 | 2016-08-23 15:09:33.288307 | 166 | "source"=>"BAN (2016-05)" | **Route de Champ Fournier** |  | area |  | 01084B004 |  |  | 79 |
| 01084 | 14303 | ban-group-f282510235644c43bfb6a4465df9ebd2 | 2 | 2016-07-20 09:26:06.542851 | 11 | 2016-08-23 15:13:29.18519 | 165 | "source"=>"BAN (2016-05)" | **Route de Champ Fournier** |  | area |  | 01084B045 |  |  | 79 |
| 01084 | 14279 | ban-group-cd06934ba3094e3ba1b4be61893925c2 | 2 | 2016-07-20 09:26:06.467832 | 14 | 2016-08-23 16:12:38.000733 | 170 | "source"=>"BAN (2016-05)" | **Route de Champ Fournier** |  | area |  | 01084B022 |  |  | 79 |
| 01084 | 14269 | ban-group-0da082266f834297b7befe08c03eca41 | 2 | 2016-07-20 09:26:06.43475 | 16 | 2016-08-23 15:10:47.073306 | 169 | "source"=>"BAN (2016-05)" | **Route de Champ Fournier** |  | area |  | 01084B010 |  |  | 79 |
| 01084 | 14313 | ban-group-cd6e12f1ca404e86847585e28c2a66d9 | 2 | 2016-07-20 09:26:06.575323 | 9 | 2016-08-23 15:04:20.228165 | 170 | "source"=>"BAN (2016-05)" | **Route de Champ Fournier** |  | area |  | 01084B055 |  |  | 79 |
| 01084 | 14280 | ban-group-439c7073877c4cbc8303cf9100fd5f75 | 2 | 2016-07-20 09:26:06.471233 | 9 | 2016-08-23 15:09:33.293151 | 171 | "source"=>"BAN (2016-05)" | Champ Fournier |  | area |  | 01084B021 |  |  | 79 |

| insee | pk | id | version | created_at | created_by_id | modified_at | modified_by_id | attributes | name | alias | kind | addressing | fantoir | laposte | ign | municipality_id |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 02100 | 82898 | ban-group-b0f96233518e4066b0fb8520cc735b48 | 1 | 2016-07-20 09:29:51.876773 | 14 | 2016-07-20 09:29:51.876773 | 14 | "source"=>"DGFIP/FANTOIR (2015-07)", "fantoir:date_annul"=>"1989117" | **HAM DE MACQUINCOURT** |  | way |  | 021000036 |  |  | 517 |
| 02100 | 82933 | ban-group-22fb5ff67b184237a2896d8fa6fa087f | 1 | 2016-07-20 09:29:51.990566 | 14 | 2016-07-20 09:29:51.990566 | 14 | "source"=>"DGFIP/FANTOIR (2015-07)" | LE MOULIN DE MACQUINCOURT |  | area |  | 02100B033 |  |  | 517 |
| 02100 | 82897 | ban-group-a7c13f4b21a8421dac09127bf08755ec | 1 | 2016-07-20 09:29:51.872027 | 12 | 2016-07-20 09:29:51.872027 | 12 | "source"=>"DGFIP/FANTOIR (2015-07)", "fantoir:date_annul"=>"2001115" | **HAM DE MACQUINCOURT** |  | way |  | 021000034 |  |  | 517 |
| 02100 | 82940 | ban-group-7f2891c9f0d64f0085171fba6f2e6c9c | 1 | 2016-07-20 09:29:52.009843 | 12 | 2016-07-20 09:29:52.009843 | 12 | "source"=>"DGFIP/FANTOIR (2015-07)" | PRES DE MACQUINCOURT |  | area |  | 02100B040 |  |  | 517 |
| 02100 | 82953 | ban-group-d72189f071b5408d9bf908f9307aee01 | 1 | 2016-07-20 09:29:52.049482 | 15 | 2016-07-20 09:29:52.049482 | 15 | "source"=>"DGFIP/FANTOIR (2015-07)", "fantoir:date_annul"=>"1988147" | **HAM DE MACQUINCOURT** |  | area |  | 02100B054 |  |  | 517 |
| 02100 | 82928 | ban-group-bed3fd33dd354872b937d852bc61ffd3 | 2 | 2016-07-20 09:29:51.969134 | 11 | 2016-08-23 15:10:04.861468 | 168 | "source"=>"BAN (2016-05)" | MACQUINCOURT |  | area |  | 02100B030 |  |  | 517 |

**Comment by christopheprudent** [comment]
aussi abordé par #194 ...

**Comment by odorie** [comment]
Je ferme car doublon (sans jeu de mots) avec #194
