### ISSUE TITLE
Group: Appariement RAN manquants (141730) et possibles (26619)...

### ISSUE THREAD

**Issue by cquest** [BaseAdresseNationale/api-gestion#202]
Les group de RAN ne sont pas tous appariés dans les données IGN issues du SGA.

141730 matricules de voie présents dans RAN manquent à l'appel (ce qui représente 639417 housenumbers).

Voici une liste de 26619 rapprochements possibles: 
[99_rapprochements.csv.zip](https://github.com/BaseAdresseNationale/ban/files/478057/99_rapprochements.csv.zip)

Celui-ci est fait sur le libellé simplifié comparé à celui (simplifié aussi) du SGA ou de FANTOIR.

**Comment by odorie** [comment]
3 cas se distinguent après une analyse d'un échantillon :

- **cas 1** : groupes RAN non encore chargés dans les données IGN (depuis un chargement du RAN a eu lieu)

- **cas 2** : groupes RAN appariés à une voie IGN détruite (cf #201). S'agit-il d'une destruction effectuée à bon escient ou d'un bug dans nos outils ? Quelques exemples ci-après. @christopheprudent , pourras-tu jeter un coup d'oeil ? On pourra aussi vérifier quand l'IGN fournira un export avec ces détruits.
_MATRICULE VOIE;NOM;INSEE
"03113553";"LOTISSEMENT LES CHARMILLES";"01001"
"03814525";"LOTISSEMENT LES MURIERS";"01001"
"04282684";"CHEMIN DU COLOMBIER";"01036"_

**- cas 3** : groupes RAN appariés avec une seule voie IGN. Cela pose plusieurs questions : Ces appariements N-1 (ou fusion de voies) sont-ils justifiés ? (@christopheprudent, peux-tu jeter un coup d'oeil ?)  Comment stocker/initialiser ces cas dans la ban ?  Dans l'export, on fournit un seule ligne pour ces fusions, avec le nom afnor de la voie approchant le plus la voie IGN, son matricule voie et les autres matricules voies. Peut-être faut-il revoir ce format ou la façon de le traiter ?
Exemple de voies LP : 
_MATRICULE VOIE;NOM;INSEE
"04489983";"IMPASSE DU VERGER";"01007"
"04489972";"IMPASSE DES VERGERS";"01007"
"04081630";"CLOS DES VERGERS";"01007"_

"04282702";"BOUCLE DU CENTRE";"01036"
"04361153";"RUELLE DU CENTRE";"01036"

Contenu du fichier export IGN:
_MATRICULE VOIE;NOM AFNOR;MATRICULES VOIES
04489972;IMPASSE DES VERGERS;04489972|04081630|04489983
04282702;BOUCLE DU CENTRE;04282702|04361153

**Comment by christopheprudent** [comment]
pour le cas 2, les trois exemples cités sont actifs dans le référentiel RAN (LAPOSTE)
ok pour contrôler un export plus complet fourni par IGN

pour le cas 3, les exemples cités sont OK également, de même, à importer dans la BAN

**Comment by odorie** [comment]
Merci Christophe pour ces précisions. Il s'agit donc de voies différentes dans le référentiel Poste. 

Mais à ton avis, s'agit-il de voies différentes dans la réalité (ou s'agit-il de la même voie avec des noms différents et mêmes adresses).
En gros je cherche à savoir si c'est un appariement N Poste - 1 IGN justifié dans la base IGN ? ou si la base IGN aurait dû contenir plusieurs voies pour ces exemples ?

Si c'est un vrai appariement 1-N (lié donc à nos différences de spécifications entre nos bases), il va falloir qu'on trouve comment le gérer dans la base  (cf #208) --> donc comment le stocker dans la ban

**Comment by christopheprudent** [comment]
ce sont normalement des voies de référence distinctes (non des synonymes)
pour moi, chacune des ces voies devrait au final se trouver dans la BAN

**Comment by odorie** [comment]
Je ferme ce ticket car référencé ici https://github.com/BaseAdresseNationale/donnees-initiales/issues/7 et https://github.com/BaseAdresseNationale/donnees-initiales/issues/1
