### ISSUE TITLE
description des valeurs de kind et positioning de Position

### ISSUE THREAD

**Issue by ebuard** [BaseAdresseNationale/api-gestion#203]
Les adresses IGN fournies sont à 50% localisées "à la plaque", ce qui représente plus de 12 M d'adresses, qui sont importées dans la table position dans la BAN.
Or dans position, il est difficile de remplir les attributs kind et positioning dans la BAN. En effet, dans le cas des plaques adresses, on pourrait être en kind "entrance", "building" ou "parcel" car la plaque adresse est en général sur l'entrée de la parcelle, mais elle peut aussi se situer à l'entrée de bâtiment. Dans positioning, les valeurs pourraient être "other" ou "gps". En vrai, ce sont des localisations contrôlées sur le terrain. 

Pour faciliter le mapping des bases et ne pas perdre d'informations, a-t'on la liste des valeurs possibles de kind et positioning et la description sur le terrain de chacune de ces valeurs? Je pense qu'il faudrait être très explicite pour les utilisateurs, en précisant des cas d'usage.

Merci.

**Comment by ebuard** [comment]
voir #51 .

Je me demande: 

- Parcel:  au milieu de la parcelle ou à l'entrée?

- building: au milieu du batiment ou à l'entrée? Et dans ce cas, pourquoi ne pas mettre entrance?

**Comment by cquest** [comment]
parcel peut correspondre soit au centroid de la parcelle ou à sa projection sur la voie, c'est en effet à éclaircir.
building: je pense qu'on devrait le réserver pour la position du batiment, si il s'agit d'une entrée, entrance est plus cohérent.

**Comment by odorie** [comment]
Fermé car : 
- le mauvais remplissage de kind et positionning est décrit dans le ticket #179 
- la description détaillée des différentes valeurs est dans le wiki
