### ISSUE TITLE
Non chargement de positions IGN (ou non mise en place de lien d'appariement) lors de l'initialisation ban

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/api-gestion#204]
Suite à l'initialisation ban du 24 août, nous ne retrouvons pas environ 2.5 millions d'adresses IGN dans les positions de la ban. Il s'agit d'adresses fournies par l'IGN (fichiers csv du 10 juillet) et dont nous ne retrouvons pas l'identifiant IGN dans les positions. 
Ce ticket est à relier au ticket #193

**Comment by yohanboniface** [comment]
Pas corrigé dans le dernier dump?

**Comment by odorie** [comment]
Ce ticket s'applique au dump du 24/08 (nous avons encore 2/3 tickets à faire sur ce dump pour tracer notre recette).
Nous n'avons pas encore regardé le dump reçu hier après-midi, mais ça ne va pas tarder.

**Comment by yohanboniface** [comment]
OK. Peut-être tu devrais créer un tag ou un milestone, pour pas t'y perdre après non?
Histoire de savoir quel ticket s'applique à quel "millésime" de l'init.

**Comment by odorie** [comment]
Dans le dump du 21/09, il manque environ 36 000 positions IGN. La plupart pointe dans la base IGN vers le même numéro (doublon sémantique).
Exemple de position IGN manquante : identifiant ADRNIVX_0000000261414122, numéro 5125, sur la voie "LA PARA" de fantoir 06016B085.
Dans la base IGN, il y a 2 géométries pour ce numéro : ADRNIVX_0000000261414121 et ADRNIVX_0000000261414122
Dans la BAN, on ne retrouve qu'une seule géométrie

**Comment by odorie** [comment]
Corrigé dans l'init du 30/06/2017
