### ISSUE TITLE
Identifiant IGN sur les positions et pas sur les housenumbers parent suite à l'initialisation ban

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/api-gestion#205]
Dans l'init du 24/08, il y a environ 1.1 millions de positions qui ont un identifiant IGN alors que le house number parent n'a pas d'identifiant IGN.

**Comment by cquest** [comment]
Sur le mini-dump du 21/9 il reste un peu plus de 6000 position liées à un housenumber sans identifiant IGN, ce qui est anormal.

**Comment by odorie** [comment]
Corrigé lors de l'init du 30/06/2017
