### ISSUE TITLE
Init ban du 21/09 : utilisation des mauvais exports IGN (SGA/BDUni)

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/api-gestion#206]
Ce ticket pour signaler que lors de l'init ban du 21/09, les fichiers IGN utilisés sont visiblement ceux du 23/06 (nous nous en sommes rendu compte en comparant les types d'adressage des groupes).

Il vaudrait mieux utiliser ceux du 11/07 qui sont de meilleurs qualités (reprise de notre chaine d'export pour corriger quelques codes fantoirs et comme beaucoup de choses reposent sur eux ...)

En attendant d'avoir les nouveaux exports IGN avec les détruits et les sources correctement remplis.

**Comment by cquest** [comment]
Oui, je confirme, sur la prochaine itération je passerai sur les derniers reçus (11-07 ou nouveaux)
