### ISSUE TITLE
RAN Group: matricule voie (co_voie) multiples ?

### ISSUE THREAD

**Issue by cquest** [BaseAdresseNationale/api-gestion#209]
Il me semblait qu'il n'y avait qu'une seul matricule voie mais plusieurs CEA si une voie était distribuée par plusieurs CP.

Sur 06 et 33 j'ai 31 cas de voies homonymes mais avec 2 matricules (avec CP identiques ou différents).

Que faire dans ce cas ?

```
select co_insee, lb_voie, count(*), array_agg(co_voie) as co_voie,
array_agg(distinct(co_postal)) as co_postal from ran_group
where co_insee like '33%' or co_insee like '06%'
group by 1,2 having count(*)>1 order by 3 desc;

 co_insee |              lb_voie               | count |      co_voie      |   co_postal   
----------+------------------------------------+-------+-------------------+---------------
 06004    | ALLEE DES MIMOSAS                  |     2 | {67727,67477}     | {06160,06600}
 06004    | AVENUE DES CHENES                  |     2 | {67938,4085160}   | {06160,06600}
 06004    | AVENUE DES FLEURS                  |     2 | {67651,68044}     | {06160,06600}
 06029    | BOULEVARD DES PINS                 |     2 | {70065,80688}     | {06150,06400}
 06069    | RUE DU 11 NOVEMBRE                 |     2 | {3538458,2835610} | {06130}
 06088    | AVENUE DES CHENES                  |     2 | {75518,4098802}   | {06100,06300}
 06088    | AVENUE DU PRINTEMPS                |     2 | {74641,75292}     | {06000,06200}
 06155    | AVENUE DES MIMOSAS                 |     2 | {79811,3592188}   | {06220}
 06161    | ALLEE DES MIMOSAS                  |     2 | {80467,4185855}   | {06270}
 33018    | RUE DES ECOLES                     |     2 | {582322,4322983}  | {33240}
 33063    | PLACE DES MARTYRS DE LA RESISTANCE |     2 | {3954642,586988}  | {33000,33200}
 33063    | RUE CAMILLE SAINT SAENS            |     2 | {3954644,587003}  | {33000,33200}
 33063    | RUE COMMANDANT CHARCOT             |     2 | {3954630,586767}  | {33000,33200}
 33063    | RUE COROT                          |     2 | {3954633,587788}  | {33100,33200}
 33063    | RUE DE LACANAU                     |     2 | {586883,3954637}  | {33000,33200}
 33063    | RUE JEAN JACQUES ROUSSEAU          |     2 | {3954643,586999}  | {33000,33200}
 33063    | RUE KLEBER                         |     2 | {3954627,587492}  | {33200,33800}
 33063    | RUE MARECHAL JOFFRE                |     2 | {586874,3954635}  | {33000,33200}
 33063    | RUE PIERRE LOTI                    |     2 | {587517,3954639}  | {33200,33800}
 33174    | LIEU DIT LAGUE SUD                 |     2 | {594687,4352277}  | {33126}
 33236    | ALLEE DES ECUREUILS                |     2 | {598612,4496033}  | {33950,33970}
 33236    | ALLEE DES GRIVES                   |     2 | {4323965,598615}  | {33950,33970}
 33236    | ALLEE DES RAMIERS                  |     2 | {4323957,598632}  | {33950,33970}
 33236    | ALLEE DES TOURTERELLES             |     2 | {4323958,598643}  | {33950,33970}
 33236    | AVENUE DES AJONCS                  |     2 | {4323959,4197999} | {33950,33970}
 33236    | AVENUE DES GENETS                  |     2 | {598923,4323963}  | {33950,33970}
 33236    | RUE DES TAMARIS                    |     2 | {4323967,598959}  | {33950,33970}
 33374    | RUE DE LA GRAVIERE                 |     2 | {4526032,4526046} | {33820}
 33529    | AVENUE DE VERDUN                   |     2 | {616486,614511}   | {33260}
 33529    | AVENUE PASTEUR                     |     2 | {614526,616445}   | {33115,33260}
 33529    | RUE GUYNEMER                       |     2 | {614760,616526}   | {33260}
(31 lignes)
```

**Comment by christopheprudent** [comment]
ta première remarque est bonne : pour 1 voie de référence (1 seul matricule voie), il y a autant de CEA que de CP 
en général 2, exception : CHEMIN DU GENIE (matricule 75898) qui a 3 CEA

par contre, il existe des voies homonymes, avec des CP différents, et dans ce cas autant de matricule Voie que de telles voies de référence
mais en plus ces voies homonymes peuvent également être multi-CP
et dans ce cas, il n'y a souvent qu'une occurrence dans la BAN

ex sur ANTIBES / JUAN LES PINS

matricule Voie|nb CP|occurrence BAN|INSEE|libellé Voie
--------------|-----|--------------|-----|------------
67407|2|1|06004|ROUTE DE LA BADINE
67408|2|1|06004|CHEMIN FOURNEL BADINE
67515|2|1|06004|BOULEVARD DU PRESIDENT WILSON
68038|2|1|06004|CHEMIN DE SAINT MAYMES
4348941|2|1|06004|VOIE TRIPODI

je suis justement en train d'affiner l'analyse du dump du 21/9 ...

**Comment by cquest** [comment]
Donc si on a 2 matricules différents, c'est que l'on a vraiment 2 voies différentes sur le terrain mais homonymes ?
31 cas sur 2 départements, ça me semble quand même beaucoup, j'imaginais ces cas comme très très rares.
Ensuite se posera la question de comment faire rentrer ça dans notre modèle... si on s'est bien compris ;)

**Comment by christopheprudent** [comment]
oui, il s'agit de cas terrains, d'où l'importance aussi de prévoir la gestion de l'attachement à la fameuse "L5" pour pouvoir les distinguer (dans certains cas)

INSEE|ID|VOIE             |CP|L5|L6
-----|---:|-----------------|-----|--------------|-------
06004|67651|AVENUE DES FLEURS|06600||ANTIBES
06004|68044|AVENUE DES FLEURS|06160|JUAN LES PINS|ANTIBES

**Comment by christopheprudent** [comment]
pour prendre un  cas et comparer le contenu BAN / RAN, avec le lien de rapprochement réalisé dans la colonne ID (matricule Voie)

n'ayant pas le  CP associé à la voie, il est difficile de "valider" cette donnée...

- BAN

INSEE|ID|VOIE             |CP|L5|L6
-----|---:|-----------------|-----|--------------|-------
06004|00067650|Allée des Fleurs Super Antibes|||Antibes
06004||AV DES FLEURS CAP||| Antibes
06004|00067651|Avenue des Fleurs Laval||| Antibes
06004|00067519|Impasse des Fleurs||| Antibes
06004||ALL DES FLEURS SARAMARTEL||| Antibes
 

- RAN

INSEE|ID|VOIE             |CP|L5|L6
-----|---:|-----------------|-----|--------------|-------
06004|67519|IMPASSE DES FLEURS|06160|JUAN LES PINS|ANTIBES
06004|67650|ALLEE DES FLEURS|06600||ANTIBES
06004|67651|AVENUE DES FLEURS|06600||ANTIBES
06004|68044|AVENUE DES FLEURS|06160|JUAN LES PINS|ANTIBES

**Comment by odorie** [comment]
Ticket proche du #41. Voir avec la Ban Team pour en supprimer au moins un.

**Comment by odorie** [comment]
Ticket déplacé dans https://github.com/BaseAdresseNationale/donnees-initiales/issues
