### ISSUE TITLE
retours sur analyse DUMP 21/9

### ISSUE THREAD

**Issue by christopheprudent** [BaseAdresseNationale/api-gestion#210]
pour commencer, voir les commentaires en fin du ticket #154 

pour les `Municipality` et `Postcode`, les détails des écarts annotés dans le ticket #154 
pour les `Group`, les questions de @cquest m'ont devancées, voir les échanges du ticket #209 et #102 

pour les `Housenumber`, c'est en fait déjà plus compliqué à suivre
voici qqs cas d'anomalies:
- avec number à 0 (quand même 3809 occurrences trouvées)
  est-ce là aussi une réalité terrain ? non référencé (et pas possible) en interne LA POSTE...
- erreur rapprochement de la voie associée

ex du n° 103 sur avenue de Thorenc ci-dessous, ok pour les autres numéros

| DB | INSEE | VOIE | ID | NUMERO | EXTENSION | CP | CEA |
| --- | --- | --- | --: | --- | --- | --- | --- |
| BAN | 06003 | Avenue de Thorenc | 4123059 | 103 |  | 06750 | **06003222N6** |
| RAN | 06003 | AVENUE MARGUERITE | 67374 | 103 |  | 06750 | **06003222N6** |
| BAN | 06003 | Avenue de Thorenc | 4123059 | 130 |  | 06750 | 06003222IT |
| RAN | 06003 | AVENUE DE THORENC | 4123059 | 130 |  | 06750 | 06003222IT |
| BAN | 06003 | Avenue de Thorenc | 4123059 | 131 |  | 06750 |  |
| BAN | 06003 | Avenue de Thorenc | 4123059 | 227 |  | 06750 | 06003222LM |
| RAN | 06003 | AVENUE DE THORENC | 4123059 | 227 |  | 06750 | 06003222LM |
| BAN | 06003 | Avenue de Thorenc | 4123059 | 500 |  | 06750 | 06003222RR |
| RAN | 06003 | AVENUE DE THORENC | 4123059 | 500 |  | 06750 | 06003222RR |
- souci appariement voie, du fait des cas cités dans #209

| DB | INSEE | VOIE | ID | NUMERO | EXTENSION | CP | CEA |
| --- | --- | --- | --: | --- | --- | --- | --- |
| BAN | 06004 | Avenue des Chênes Salis | 67938 | 17 |  | 06160 | **0600422SRM** |
| RAN | 06004 | AVENUE DES CHENES | 4085160 | 17 |  | 06160 | **0600422SRM** |
| BAN | 06004 | Avenue des Chênes Salis | 67938 | 63 |  | 06160 | **0600422SRN** |
| RAN | 06004 | AVENUE DES CHENES | 4085160 | 63 |  | 06160 | **0600422SRN** |
| BAN | 06004 | Avenue des Chênes Salis | 67938 | 70 |  | 06160 | **0600422SRP** |
| RAN | 06004 | AVENUE DES CHENES | 4085160 | 70 |  | 06160 | **0600422SRP** |

il existe en effet plusieurs occurrences de voies

| INSEE | ID | VOIE | CP | L5 | L6 |
| --- | --: | --- | --- | --- | --- |
| 06004 | 67981 | AVENUE DES CHENES VERTS | 06160 | JUAN LES PINS | ANTIBES |
| 06004 | 68036 | AVENUE DU PARC DES CHENES VERTS | 06160 | JUAN LES PINS | ANTIBES |
| 06004 | 4085160 | AVENUE DES CHENES | 06160 | JUAN LES PINS | ANTIBES |
| 06004 | 67938 | AVENUE DES CHENES | 06600 |  | ANTIBES |

et voici la situation RAN pour ce numéro 17, qui existent sur les 2 voies

| INSEE | ID | VOIE | CP | L5 | L6 | NUMERO | EXTENSION | CEA |
| --- | --: | --- | --- | --- | --- | --- | --- | --- |
| 06004 | 4085160 | AVENUE DES CHENES | 06160 | JUAN LES PINS | ANTIBES | 17 |  | 0600422SRM |
| 06004 | 67938 | AVENUE DES CHENES | 06600 |  | ANTIBES | 17 |  | 0600422IZ3 |

côté BAN

| INSEE | VOIE | ID |
| --- | --- | --: |
| 06004 | Avenue des Chênes Haut Lauvert |  |
| 06004 | PARC DES CHENES VERTS | 00068036 |
| 06004 | Avenue des Chênes Verts | 00067981 |
| 06004 | Avenue des Chênes Salis | 00067938 |

il manque donc l'occurrence de la voie, de matricule 4085160, 
le numéro 17 existant, associé à la voie, de matricule 67938, porte en fait un CEA différent 0600422IZ3
et enfin il manque le numéro 17, associé à la voie, de matricule 4085160, avec le CEA 0600422SRM

**Comment by cquest** [comment]
Cas des numéros "0":
- il en existe bien quelques uns sur le terrain, mais sûrement pas 3850 sur 2 départements... à vérifier côté IGN

**Comment by cquest** [comment]
Pour l'erreur de rapprochement, c'est à revérifier lorsque l'issue 102 sera rectifiée.

**Comment by christopheprudent** [comment]
à noter que la rattachement d'un Group peut et doit se faire à une éventuelle "L5" d'une commune
celle-ci pouvant être une ancienne commune (avec un code INSEE inactif), ou pas

export d'un nouveau flux des voies, pour donner cet attachement
insee;matricule Voie;code postal;type voie;libellé voie (complet);cea;libellé l5;insee l5(si existant)

**Comment by odorie** [comment]
A fusionner vraisemblablement avec #175. Et faire des sous-tickets sur les problématiques restantes.

**Comment by odorie** [comment]
Déplacement dans le dépôt d'init https://github.com/BaseAdresseNationale/donnees-initiales/issues
