### ISSUE TITLE
postcode manquants sur housenumber avec CEA

### ISSUE THREAD

**Issue by cquest** [BaseAdresseNationale/api-gestion#211]
Sur le minidump du 21/09, près de 200.000 codes postaux n'étaient pas renseignés sur les housenumber portant un CEA.

Je viens de modifier l'init à ce niveau et on a maintenant un résidu de 2232 codes postaux manquants.
https://github.com/BaseAdresseNationale/ban/commit/0fee485c9b07f9e47dde0080788a588a84122fc6
https://github.com/BaseAdresseNationale/ban/commit/aadab8c3bfe4c21482e723d137db0cb6b7b097e3

Je prépare un nouveau minidump pour que @christopheprudent puisse vérifier ce point.

**Comment by christopheprudent** [comment]
dump 20160929 restauré (partie Housenumber) bien mieux !
avec les écarts:

data|delta|count
:----|-----|-----:
Housenumber|-|55125
Housenumber|!|4055
Housenumber|+|182485

en moins dans la BAN: 55125 au lieu de 192100
par contre, avec augmentation des écarts d'attributs (au hasard code postal), qui passe de 2662 à 4055...

**Comment by christopheprudent** [comment]
voici en fait la répartition des attributs différents dans le cas ! (delta en modification)

avec pour rappel

data  |  attributs
:-----|:----
Housenumber | code, id, number, ordinal

attribut | count
:--------|------:
code|0
id|3894
number|3
ordinal|160

2 cas partagent deux attributs
cea 3355022T2Z à la fois (id, ordinal)
cea 33056224HV à la fois (number, ordinal)

**Comment by odorie** [comment]
Je déplace ce ticket dans le dépôt d'init https://github.com/BaseAdresseNationale/donnees-initiales/issues
