### ISSUE TITLE
gestion de la désactivation & redirection d'une ressource

### ISSUE THREAD

**Issue by christopheprudent** [BaseAdresseNationale/api-gestion#237]
dans l'outil de fiabilisation des voies d'une commune, nous avons le besoin de gestion de la désactivation des doublons et donc de leur redirection

se pose alors quelques questions ...
1. la première est que, pour l'instant, c'est au client de l'API de gérer la désactivation de la ressource, puis d'enchaîner la demande de redirection de celle-ci, vers la ressource de référence
   cette opération n'étant pas atomique, il y a donc un risque de dénaturer la BAN
2. ensuite se pose la question concernant les éventuelles ressources filles de la ressource à désactiver
   avec le même corollaire de transaction atomique
- désactiver un `Group` : quid  des ressources `Housenumber` et `Position` ?
- désactiver un `Housenumber` : quid  des ressources `Position` ?

la redirection revient-elle à:
créer les ressources fille manquante de la ressource de référence,
rediriger chaque ressource fille vers la ressource fille correspondante de la ressource de référence
rediriger la ressource parente

prenons l'exemple d'un `Group` avec 2 doublons dans la BAN

| Group | Housenumber | Etat |
| --: | --: | --: |
| ban-group-id1 | 1, 3, 7 | référence |
| ban-group-id2 | 1, 5, 7 | doublon |

créer Housenumber 5 pour ban-group-id1
rediriger les Housenumber de ban-group-id2 vers leurs homologues de ban-group-id1
rediriger le Group ban-group-id2 vers ban-group-id1

**Comment by christopheprudent** [comment]
se repose en fait l'utilité du mode CASCADE pour les opérations de désactivation ou de suppression
voir aussi ticket #81 au sujet de la suppression

**Comment by yohanboniface** [comment]
>  cette opération n'étant pas atomique, il y a donc un risque de dénaturer la BAN

Je ne partage pas ce constat. De mon point de vue, les redirections sont des informations "secondaires", elles n'ont aucun caractère obligatoire ou indispensable.

Globalement, je ne suis pas sûr de comprendre quelle est l'action attendue sur ce ticket.

Pour moi, quand on veut supprimer une resource, le workflow est:

- s'il y a des resources pointant vers cette resource, définir quoi faire pour chacune (changer son parent? La supprimer? On ne peut pas automatiser ces choix)
- supprimer la resource
- créer une redirection éventuelle (il y a des suppressions qui ne demanderont pas de redirection, par exemple une resource créée par erreur puis supprimée dans la foulée)

De mon point de vue, ces opérations demandent une intervention humaine pour arbitrer granulairement chaque action, et donc je pense qu'on ne peut pas automatiser beaucoup plus le workflow.
Mais je peux rater un truc :)

**Comment by christopheprudent** [comment]
la question est alors celle du contrôle en place dans l'API : une demande de suppression sera t-elle refusée si il existe encore des éléments fils actifs pour la ressource demandée ?
à charge de l'appelant de traiter ces éléments fils, AVANT de finaliser la suppression

par ailleurs, j'insiste quand même sur l'aspect atomique de la transaction : suppression suivi de la redirection, 
si ces 2 actions sont séparées, on peut avoir un peu tous les cas possibles en base sinon: là aussi, quels sont les contrôles faits par l'API ?

enfin, en ce qui concerne l'outil de fiabilisation des voies, voici notre orientation:

- désactiver tous les éléments fils d'une voie, validée en doublon, en partant des positions, puis des numéros
- désactiver la voie en doublon
- rediriger celle-ci vers la voie de référence

là aussi, vient une autre question  :stuck_out_tongue_winking_eye:
est-il utile de rediriger ces éléments fils, en plus de la redirection de la voie ?

nous pourrons échanger davantage lors de notre prochaine audio BAN...

**Comment by yohanboniface** [comment]
> a question est alors celle du contrôle en place dans l'API : une demande de suppression sera t-elle refusée si il existe encore des éléments fils actifs pour la ressource demandée ?

Oui, c'est le cas. Cf discussions sur #81

> à charge de l'appelant de traiter ces éléments fils, AVANT de finaliser la suppression

Absolument.

> si ces 2 actions sont séparées, on peut avoir un peu tous les cas possibles en base sinon: là aussi, quels sont les contrôles faits par l'API ?

De mon point de vue, la redirection n'est pas "obligatoire" stricto sensu.
Mais bien sûr on peut réfléchir à changer l'API pour aller dans cette direction.
Le truc c'est qu'un même DELETE peut donner lieu à plusieurs redirection (insee + siren ou fantoir + laposte + ign…). Et il y a aussi des DELETE qui ne vont donner lieu à aucune redirection.
Et bien sûr des redirections qu'on va créer en dehors de tout DELETE.

>  est-il utile de rediriger ces éléments fils, en plus de la redirection de la voie ?

Pas forcément sur tous les champs. Par exemple,  je pense qu'en l'état c'est inutile de le faire sur les identifiants BAN, vu que la BAN n'existera que depuis très peu de temps, et donc ces identifiants ne seront certainement pas utilisés.
En revanche, ça peut être intéressant de le faire pour les identifants externes (genre ign ou laposte), puisqu'on peut estimer que des systèmes externes les utilisent (à commencer par l'IGN ou La Poste).
Après on peut simplifier et créer des redirections sur tous les champs, ça va générer de la donnée pour rien, mais peut-être pas tant que ça.

**Comment by odorie** [comment]
La dernière solution proposée est-elle validée par la Ban Team ?

**Comment by yohanboniface** [comment]
> La dernière solution proposée est-elle validée par la Ban Team ?

Si tu parles de la redirection des housenumbers quand une voie en doublon est supprimée au profit d'une autre, ce n'est pas l'API qui le gère (en l'état), c'est à la charge du client qui fait le boulot.
