### ISSUE TITLE
problème lors de l'init: mauvaises attributions de Kind pour les Group

### ISSUE THREAD

**Issue by ebuard** [BaseAdresseNationale/api-gestion#256]
Concernant l'initialisation de la BAN:
J'ai noté certaines anomalies de la table Group pour les département 06 et 33. Certains objets de Group ont un Kind = area, alors que ce sont des linéaires, dénommés "rue de" "chemin de". Exple: « chemin du ribouriaou » à Biot avec gr_fantoir= 06010B025.
Inversement, d'autres ont un Kind = way, alors que ce sont des zones. Exple: « zone ind des croutons » à Antibes.

Il faudrait corriger ça, en se basant peut-être sur des mots directeurs.

**Comment by christopheprudent** [comment]
en effet, voir l'élément https://github.com/BaseAdresseNationale/ban/wiki/init-des-donn%C3%A9es du wiki, qui se proposait de choisir ce type (way, area) selon le type de voie...

**Comment by odorie** [comment]
Nettement améliorer lors de l'init du 30/06
