### ISSUE TITLE
ajout de contraintes dans l'API

### ISSUE THREAD

**Issue by gschittek** [BaseAdresseNationale/api-gestion#257]
Lors de nos tests fonctionnels sur l'API, nous avons constaté qu'il était possible de renseigner des valeurs non conformes sur les classes et champs suivants : 
- municipality/insee : "abcde" (chaine de 5 caractères)
- municipality/siren : "test" (chaine de moins de 9 caractères)
- group/laposte : "test" (chaine de moins de 10 caractères)
- group/ign : "test" (chaine de moins de 24 caractères)
- housenumber/number : "test" (chaine de moins de 16 caractères)

Serait-il possible d'ajouter des contraintes à ces champs ? 
- municipality/insee : regexp du style "/^(2[AB]|[0-9]{2})[0-9]{3}$/"
- municipality/siren : entier à 9 chiffres
- group/laposte : 8 caractères
- group/ign : 9 caractères
- housenumber/number : entier

**Comment by yohanboniface** [comment]
Oui.
En revanche je comprends pas la demande sur housenumber.number.

**Comment by yohanboniface** [comment]
> group/laposte : 8 caractères

@christopheprudent une regex en particulier pour ce champ (c'est le matricule)?
Je veux bien la réponse pour les champs HouseNumber.laposte et Position.laposte (où c'est le CEA).

> group/ign : 9 caractères

Que pour Group ou aussi pour HouseNumber et Position?

**Comment by yohanboniface** [comment]
>  En revanche je comprends pas la demande sur housenumber.number.

Ah, j'ai compris, ce qui est entre parenthèses dans la première liste à puce, c'est ce qu'il y a, et dans la seconde liste à puce, ce que tu veux. M'a fallu mon deuxième neurone apparemment ;)
Et du coup, ça va pas marcher: un numéro peut contenir une lettre (qui n'est pas l'indice de répétition). Par exemple https://github.com/osm-fr/bano/issues/67

**Comment by christopheprudent** [comment]
la contrainte pour la clé POSTE (code CEA) : 10 caractères fixes
ce code est composé d'un code INSEE (regex déjà défini) suivi de 5 caractères (parmi 234679ABCEGHILMNPRSTUVXYZ)

**Comment by yohanboniface** [comment]
> ce code est composé d'un code INSEE (regex déjà défini) suivi de 5 caractères (parmi 234679ABCEGHILMNPRSTUVXYZ)

Tu veux qu'on mette un regex précise? Il manque 1, 5, 8, D, etc., tu me confirmes que c'est bien le cas?

> sinon, pour l'autre clé POSTE (matricule Voie) : entier

OK, donc je mets un integer field (i.e. pas de contrainte de taille) ?

**Comment by christopheprudent** [comment]
- pour le code CEA
c'est ça, INSEE + 5 caractères fixes, appartenant à l'ensemble cité (auquel il manque en effet les caractères 0, 1, 5, 8, D, etc ...)
une regex me parait bien, cela pourra éviter de renseigner des mauvaises valeurs, 
de plus, cette valeur doit être unique

- pour le matricule
il s'agit d'un entier (séquence), donc pour nous pas de limite : la représentation choisie est en String, mais avec 8 caractères disponibles, cela me semble OK (99 millions de voie distinctes,  :smirk:)
de même, c'est une valeur unique

**Comment by christopheprudent** [comment]
par contre, dans le SI POSTE, un numéro est forcément numérique (avec extension possible BIS, TER, ... aussi appelée indice de répétition à l'IGN)

**Comment by yohanboniface** [comment]
> par contre, dans le SI POSTE, un numéro est forcément numérique (avec extension possible BIS, TER, ... aussi appelée indice de répétition à l'IGN)

Vous traitez comment ce genre de cas alors http://www.openstreetmap.org/search?query=lotissement%20le%20val%20de%20gravel#map=20/48.47914/-2.17029&layers=H ?

**Comment by christopheprudent** [comment]
j'avais regardé le cas cité
ces numéros sont déclarés en numérique (réalité du terrain, je ne sais pas)

LB_COMMUNE	LB_VOIE	CO_VOIE	CO_POSTAL	NUM_VOIE	LB_EXT	CO_CEA_NUMERO
CORSEUL	LOTISSEMENT DU VAL DE GRAVEL	319637	22130	1	A	22048222XC
CORSEUL	LOTISSEMENT DU VAL DE GRAVEL	319637	22130	1	B	220482232Y
CORSEUL	LOTISSEMENT DU VAL DE GRAVEL	319637	22130	1	C	220482232Z
CORSEUL	LOTISSEMENT DU VAL DE GRAVEL	319637	22130	1	D	2204822332
CORSEUL	LOTISSEMENT DU VAL DE GRAVEL	319637	22130	1	E	2204822333
etc ...

**Comment by yohanboniface** [comment]
OK.
Il me semble qu'on avait des cas plus complexes.
cc @cquest dont la mémoire marche mieux que la mienne :)

**Comment by vinyll** [comment]
Based on @christopheprudent's suggestion:
`/^(2[AB]|\d{2})\d{3}$/` for an insee/municipality

**Comment by cquest** [comment]
Il y a des cas plus tordus et complexes sur les numéros qu'on peut considérer comme numéro/sous-numéro. Ils ne sont pas dans les bases actuelles, mais peuvent exister sur le terrain.

Exemple: 100.1

**Comment by yohanboniface** [comment]
Du coup je garde le field en CharField?

**Comment by yohanboniface** [comment]
Au passage (je pensais qu'on l'avait fait, mais je trouve pas trace dans le wiki), ce serait bien de les référencer, ces cas "tordus".

**Comment by cquest** [comment]
Il y a des cas plus tordus et complexes sur les numéros qu'on peut considérer comme numéro/sous-numéro. Ils ne sont pas dans les bases actuelles, mais peuvent exister sur le terrain.

Exemple: 100.1

**Comment by odorie** [comment]
Faire un point spécifique sur les champs restants à contrôler ?

**Comment by yohanboniface** [comment]
Je suggère de fermer ici et d'ouvrir des tickets spécifiques si nécessaire, sur le mode "un ticket = une action".
