### ISSUE TITLE
Performance de la requête géographique avec des ressources liées

### ISSUE THREAD

**Issue by odorie** [BaseAdresseNationale/api-gestion#258]
Le premier prototype du guichet adresse v2 affiche les points adresses (géométrie et numéro) sur une page web : 
 
![guichetv2](https://cloud.githubusercontent.com/assets/16690380/20487443/96371914-b003-11e6-87c8-75a85f5c8386.png)

Quand on clique sur un des points une fiche informative présente le nom du groupe, le nom de la commune ...

Nous observons des temps de réponses de l'ordre de plusieurs secondes (parfois plus de 10 secondes) aux requêtes que nous faisons à l'API (2 niveaux d'objets liés : fields=*.*.*, et une centaine d'objets).

Exemple de requêtes : 

http://rks0911w262.ign.fr:5959/housenumber?west=-0.24&south=44.90&east=-0.22&north=44.91
20 objets en 89 ms
100 objets en 250 ms
200 objets en 450 ms
500 objets en 1000 ms

http://rks0911w262.ign.fr:5959/housenumber?west=-0.24&south=44.90&east=-0.22&north=44.91&fields=*
20 objets en 180 ms 
100 objets en 700 ms
200 objets en 1300 ms
500 objets en 3250 ms

http://rks0911w262.ign.fr:5959/housenumber?west=-0.24&south=44.90&east=-0.22&north=44.91&fields=*.*
20 objets en 390 ms 
100 objets en 1750 ms
200 objets en 3550 ms
500 objets en 8850 ms

http://rks0911w262.ign.fr:5959/housenumber?west=-0.24&south=44.90&east=-0.22&north=44.91&fields=*.*.*
20 objets en 690 ms 
100 objets en 3200 ms
200 objets en 6700 ms
500 objets en 17200 ms

Du coup, le proto n'est pas très fluide. Nous interrogeons sur 2 niveaux d'objets pour faire apparaitre le nom de la commune dans la fiche d'informations de l'objet. Nous pourrions passer à un niveau et aller chercher le troisième lors de la demande d'affichage de la fiche d'information, mais ça manquerait encore de fluidité.

Nous sommes à la recherche d'une solution : 
- meilleur configuration serveur (il faudrait peut-être confirmer ces tests sur un autre serveur ...)
- amélioration de l'API
- trouver une autre méthode pour faire cet affichage

**Comment by odorie** [comment]
L'amélioration de cette requête est importante pour le guichet adresse v2 et on peut temporiser pour l'instant en attendant que les dév du guichet v2 avancent

**Comment by yohanboniface** [comment]
On peut peut-être commencer par:
- vérifier qu'il y a les bons index en base (notamment sur la géométrie, puisqu'on filtre sur la bbox)
- faire une requête à un seul niveau, et ne demander les objets liés qu'au clic sur l'objet
