### ISSUE TITLE
Ajout d'un champ Statut sur les clients

### ISSUE THREAD

**Issue by ebuard** [BaseAdresseNationale/api-gestion#268]
Pour assurer une meilleure traçabilité des données BAN (et pour pouvoir réaliser les synchronisations IGN et La Poste, rajouter un champ statut sur les clients pour identifier: les mairies, les communautés de communes, La Poste, IGN, crowdsourcing...
Créer une liste d'énumérés pour fixer ces statuts dès le départ.

**Comment by jdesboeufs** [comment]
Est-ce que tu peux préciser un peu ?
Sur quels endpoints de l'API ce champs va t'il être utilisé ?

Merci :)

**Comment by ebuard** [comment]
Ce champ pourrait être exposé à minima dans le diff, et pourquoi dans les get et les versions.
Actuellement on expose l'id du client ayant créé/modifié l'objet. 
On pourrait ajouter son statut : par exemple on pourrait savoir que tel objet a été créé par une mairie ou par l'IGN ou La Poste directement dans le get ou le diff.

**Comment by odorie** [comment]
Après discussion BAN Team de ce jour, ajouter un champ attribute sur la session qui pourra contenir ces précisions.

**Comment by gschittek** [comment]
J'ai ajouté un champ attribut a la session, qui est optionnel, a renseigner lors de la demande de token (POST). Ce champ est affiché dans les created_by et modified_by des versions et diff.

Poussé dans la branch scopes
