### ISSUE TITLE
Fusionner autant que possible les positions de même kind

### ISSUE THREAD

**Issue by ebuard** [BaseAdresseNationale/api-gestion#270]
Si deux positions sont proches et de même kind, les fusionner.

**Comment by ebuard** [comment]
Autrement dit: créer une multi-position ou n positions?

**Comment by yohanboniface** [comment]
Il faudrait établir des règles pour ça: selon les sources, de qui garde-t-on quel champ(s) lors de la fusion?

**Comment by odorie** [comment]
Des règles suivantes ont été mise en oeuvre pour l'init du 30/06 : on garde autant que possible une seule position entrance. Si une position "entrance" bano et une position entrance "ign" sont éloignées de plus de 5 m, on garde les 2 positions.
Si une position entrance bano et un position IGN "projeté de centre parcelle" ou "interpolée", on garde uniquement position bano.
Ces règles sont susceptibles d'évoluer suite aux recettes
