### ISSUE TITLE
Créer un atelier pilote en prod avec données jetables

### ISSUE THREAD

**Issue by ebuard** [BaseAdresseNationale/api-gestion#271]
Proposition: créer un atelier pilote en environnement de prod (lecture/écriture par des utilisateurs test, IGN, La Poste... avec des données jetables) pour vérifier les droits, lecture/écriture.
1 mois?

**Comment by yohanboniface** [comment]
Pourquoi faire ça en prod? Ne peut-on pas anticiper ça sur un serveur de dev/préprod?

**Comment by ebuard** [comment]
D'accord avec toi.

**Comment by odorie** [comment]
Instance de prod ouverte pour test sur quelques départements le 30/06
