### ISSUE TITLE
Exports

### ISSUE THREAD

**Issue by yohanboniface** [BaseAdresseNationale/api-gestion#3]
We need to export open data, in various format (csv, sjson…), for various areas (France, départements…), and with various flavours (default, postal, which gives priority to postal positions, aid, which gives priority to aid positions, etc.).

**Comment by yohanboniface** [comment]
Ad first iteration, I've made the choice to have just a flat resources export, and to deal later with some client API that will process it and develop it in other formats and flavours.

More thinking needed, though :)

**Comment by ebuard** [comment]
Proposition: faire un export csv qui produit des fichiers départementaux (comme la BAN V0). 
Pour cela, faire une commande python avec 1 ou n départements en entrée?
Question à régler: pour 1 hn, exporte t-on 1 ou n positions? Comment filtrer?

**Comment by jdesboeufs** [comment]
Il faudrait définir un ordre de priorité lors de l'export, ou en dur.
On ne diffuserait qu'une version, mais un jour, si l'API Export est suffisamment performante, peut-être que les utilisateurs pourront le faire par eux-même, en fonction de leurs besoins.

**Comment by odorie** [comment]
La première version de l'export est disponible : ban v1 en json et ban v0 en csv
