### ISSUE TITLE
retours sur écarts BAN/RAN au 30/6/2017 (départements 06 et 90)

### ISSUE THREAD

**Issue by christopheprudent** [BaseAdresseNationale/api-gestion#335]
j'ai repris les comparaisons sur le modèle #154 
et voici les résultats:

| data | delta | count |
| :-- | --- | --: |
| Group | - | 428 |
| Group | ! | 4553 |
| Group | + | 25414 |
| Housenumber | - | 7776 |
| Housenumber | ! | 1596 |
| Housenumber | + | 80375 |

je pense que le lien Voie / L5 est toujours source de souci (voir #209), 
par ailleurs, il reste aussi le souci des voies multi-CP, des numéros à 0 (inconnu LA POSTE), 

pour chaque élément d'adresse (Municipality, Postcode, Group, Housenumber), la comparaison se base sur les clés suivantes, avec les écarts en plus, en moins notés +, - 

| data | key |
| :-- | :-- |
| Municipality | insee |
| Postcode | code, name |
| Group | laposte_id |
| Housenumber | laposte_cea |

et en cas d'égalité des clés, les écarts en modification, notés !, pour leurs attributs différents:

| data | attributes |
| :-- | :-- |
| Municipality | name |
| Postcode | insee |
| Group | name, l5_insee, id, code |
| Housenumber | id, code, number, ordinal |

**Comment by ebuard** [comment]
Merci Christophe.

Si je résume, vous perdez 448 groupes et 776 housenumbers.
En reprenant tes chiffres sur les deux dernières initialisations:

-  on avait des rapports d'objets perdus par rapport au objets gagnés de 40% sur les groupes et 77% sur les housenumbers (initialisation du 1 er aout 2016)

- on a maintenant un rapport de 1.6 % sur les groupes et 9.6% sur les housenumbers

Ce qui veut dire que l'initialisation est (au moins 8 fois) mieux que la précédente, sur les départements 90 et 06. A vérifier quand même sur d'autres départements.

On note qu'il y a toujours 3 problèmes pour la comparaison:

1.   le lien Voie / L5 

2.   les voies multi-CP

3.   les numéros à 0

Le 3e point ne se résoudra pas: par construction, on a fait ce choix pour conserver les groupes de la DGFiP. Le 1er point est lié à la fusion de communes. On est en cours d'analyse et de résolution. Ce sera effectif pour la prochaine initialisation. Pour le 2e point, c'est compliqué à gérer puisque les voies ne sont pas liées directement au CP. On ne peut pas passer par les adresses?

Elodie

**Comment by christopheprudent** [comment]
de mémoire, il me semble que si : la voie possède un _housenumber_ (adresse) à NULL, pour pouvoir justement lier chaque CEA avec chaque code postal de cette voie...

une voie multi-CP peut donc ainsi posséder à priori 2 occurences dans _housenumber_, avec pour chacune le CEA lié au CP correspondant

**Comment by odorie** [comment]
Pour la modélisation des voies multi-CP, voici 2 exemples/propositions (cf aussi mail envoyé à Linda hier).
Je décris la modélisation Poste, puis la modélisation BAN. Pouvez-vous valider ?

**Exemple 1 : 2 voies distinctes, homonymes avec CP différents** 

Modélisation La Poste :
2 voies (matricule voie différents) dans ran_group.csv

|co_insee | co_voie  | co_postal | lb_type_voie |      lb_voie      |    cea     |     lb_l5     | co_insee_l5|
| :-- | --- | ---  | ---  | ---  | ---  | ---  | --: |
|06004    | 00067651 | 06600     | AV           | AVENUE DES FLEURS | 06004222G3 |               |
|06004    | 00068044 | 06160     | AV           | AVENUE DES FLEURS | 060042232C | JUAN LES PINS |

La voie de matricule voie 00067651 a 12 numéros
La voie de matricule voie 00068044 a 10 numéros

Modélisation dans la BAN :

- 2 voies distinctes

- 2 objets Postcode différents distincts par le cp et la ligne 5 :
o	cp1 = { cp = 06600, name = ANTIBES, complement null}
o	cp2 = { cp = 06160, name = ANTIBES, complement = JUAN LES PINS}

- 12 hn pointent vers la voie de co_voie 00067651. Un hn null supplémentaire avec cea = 06004222G3 pointe vers cette voie. Ces hns sont à rattacher à cp1.

- 10 hn pointent vers la voie de co_voie 00068044. Un hn null supplémentaire avec cea = 060042232C pointe vers cette voie. Ces hns sont à rattacher à cp2.


**Exemple  2 : même voie homonyme, multi-CP (même cea, même matricule voie)**
Modélisation La Poste :
2 voies (matricule voie identique) dans ran_group.csv

|co_insee | co_voie  | co_postal | lb_type_voie |        lb_voie        |    cea     |     lb_l5     | co_insee_l5|
| :-- | --- | ---  | ---  | ---  | ---  | ---  | --: |
|06004    | 00067408 | 06160     |              | CHEMIN FOURNEL BADINE | 060042222E | JUAN LES PINS |
|06004    | 00067408 | 06600     |              | CHEMIN FOURNEL BADINE | 060042222E |               |

La voie à 68 adresses dans les données La Poste pointant vers le matricule voie 00067408

Modélisation dans la BAN :

- Une voie

- 2 objets Postcode différents distincts par le cp et la ligne 5 :
o	cp1 = { cp = 06600, name = ANTIBES, complement null}
o	cp2 = { cp = 06160, name = ANTIBES, complement = JUAN LES PINS}

- 68 hn + 1 hn null avec cea = 060042222E. **Vers quel PostCode faire pointer ces objets** ?

**Y-a-t-il d’autres cas particuliers sur ces voies multi-CP ?**

**Comment by christopheprudent** [comment]
bonjour

ok pour exemple 1, mais souci sur exemple 2,
mais j'avais une erreur dans l'exemple, il y a bien 2 CEA différents, désolé !

|co_insee | co_voie  | co_postal | lb_type_voie |      lb_voie      |    cea     |     lb_l5     | co_insee_l5|
| :-- | --- | ---  | ---  | ---  | ---  | ---  | --: |
|06004    | 00067651 | 06600     | AV           | AVENUE DES FLEURS | 06004222G3 |               |
|06004    | 00068044 | 06160     | AV           | AVENUE DES FLEURS | **06004237I2** | JUAN LES PINS |


de manière générale, la gestion du CP pour la voie est générale : mono ou multi-CP, homonyme ou pas

dans la BAN, il me semble que le modèle est organisé comme suit:
une voie possède autant d'occurence(s) dans _Housenumber_, avec un number à NULL, qu'elle a de CP

est-ce plus clair ?

**Comment by christopheprudent** [comment]
je me suis trompé en ajoutant ce commentaire, cette fonctionnalité n'est pas encore fermée :smile:

**Comment by odorie** [comment]
Pour l'exemple 1, dans le fichier hexacle d'août 2017 que j'ai en ma possession , la voie de matricule voie 00068044 a un hexacle de 060042232C. Est-ce un souci de mise à jour ou ma version du fichier qui n'est pas correcte ?

Peux-tu préciser le résultat attendu pour l'exemple 2 ? Manque-il une ligne dans le fichier hexacle pour donner l'hexacle d'une des voies ? (cf ta réponse au ticket   [https://github.com/BaseAdresseNationale/donnees-initiales/issues/26#issuecomment-326877706]). Et à quel PostCode BAN sont reliés les housenumbers dans l'exemple 2 ?

**Comment by christopheprudent** [comment]
non, tu as bien le bon HEXACLE, mais celui-ci n'est pas "complet" pour ces voies multi-CP : le produit ne fournit qu'un seul CEA pour la voie (au lieu de 2), c'est au final un souci pour faire la mise à jour de la BAN à partir de celui-ci

pour l'exemple 2, voir le détail corrigé plus haut avec le CEA 06004237I2 (en plus), mais là aussi HEXACLE ne convient donc pas (pour la même raison)
il s'agit bien ici de 2 voies distinctes, chacune possédant des numéros, affectés au CP correspondant (06600 pour la voie sur ANTIBES même, 06160 pour la voie sur la L5 JUAN LES PINS de la commune d'ANTIBES)

est-ce plus clair ?

**Comment by odorie** [comment]
Oui, mais j'ai encore quelques doutes. Peut-on s'appeler pour les lever ? Je t'envoie un mail pour prendre contact

**Comment by odorie** [comment]
Suite à notre discussion téléphonique:

L'exemple 1 est correct (petite erreur de cea lors de nos échanges), mais la modélisation BAN proposée est correcte.

L'exemple 2 contient des anomalies: la modélisation BAN ne contient pas toute la richesse des données Poste, notamment le cea de la deuxième voie et le lien correct des hns vers les bons CP. Ceci est dû au fait que les fichiers hexacle et hexavia sont eux-aussi incomplets : il manque les mêmes données.

Pour avoir une BAN complète, on peut donc soit:
- la charger à partir de l'hexacle/hexavia, mais ensuite il faudra passer un patch pour compléter les voies multi-CP (dans la BAN cela se traduira par la modification du lien entre ces hns et les CP et la création de quelques hns nulles avec les cea).
- la charger à partir d'un csv complet généré par La Poste

**Comment by clodio** [comment]
Après analyse du dernier init, sur l'adresse concernée et sur d'autres adresses de ce type les données sont correctes.
