### ISSUE TITLE
Augmenter la durée de validité des tokens

### ISSUE THREAD

**Issue by ebuard** [BaseAdresseNationale/api-gestion#368]
Passer à un token de 6h.
Ensuite, si ça pose un problème, 24h.

**Comment by cquest** [comment]
Rallonger la durée des token ne fait que décaler le problème:
- un script long pourra se retrouver bloqué
- la sécurité est amoindrie

Le durée à durée de validité glissante, prolongé au fur et à mesure de son usage est possible sans impact important sur la base.
Lors de chaque appel à l'API, le token est vérifié,il suffirait de mettre à jour sa validité d'une heure si elle passe en dessous d'un seuil (par exemple 30mn). Du coup, cela ne fait qu'un UPDATE en base toutes les 30mn, la durée d'inactivité sera entre 30mn et 1h, les scripts peuvent tourner autant de temps qu'ils veulent, tant qu'ils utilisent leur token au moins une fois par 30mn...

**Comment by ebuard** [comment]
Création d'un token flexible
