### ISSUE TITLE
Quelle est l'utilité des CORS dans wsgi.py?

### ISSUE THREAD

**Issue by ebuard** [BaseAdresseNationale/api-gestion#370]
Pourquoi utiliser des CORS dans wsgi.py, sachant qu’il n’y a pas de filtrage sur les origines acceptées?

**Comment by cquest** [comment]
CORS n'est pas un filtrage coté serveur mais côté client.

CORS est bien nécessaire pour que l'API envoie au client HTTP les entêtes afin que celui-ci accepte de communiquer avec l'API même si l'origine de la requête provient d'un script d'un autre domaine.
