### ISSUE TITLE
Allow auth.Client creation from the API

### ISSUE THREAD

**Issue by yohanboniface** [BaseAdresseNationale/api-gestion#4]

**Comment by ebuard** [comment]
Ce serait utile notamment au guichet adresse V2 pour créer des clients à la volée (par l'API et correspondant à ses utilisateurs). Avons nous bien compris ce ticket?

**Comment by jdesboeufs** [comment]
Un "client" c'est souvent une application, et pas un utilisateur.
Mais si à terme il y a un modèle Utilisateur dans la BAN, ça change pas mal de choses.

@yohanboniface quel était l'esprit du ticket originel ? Faire une interface d'admin ?

**Comment by yohanboniface** [comment]
Oui, un client, c'est un service qui a accès à l'API, pas un humain avec dix doigts. :)
Le guichet adresse est censé gérer ses "utilisateurs" de son côté et il se connecte avec un seul client, toujours le même (mais il doit préciser l'utilisateur final lors de la création d'une session, pour des raisons de traçabilité), donc a priori il n'a pas vocation à créer des clients.

Et, oui, l'esprit du ticket était de permettre la création d'une admin tierce pour gérer les clients. On en est pas là.

On aura certainement besoin de pouvoir accéder aux clients via l'API à terme, mais ce n'est pas du tout dans les priorités clairement. On peut fermer, ou laisser ouvert sans milestone, à mon avis.

**Comment by ebuard** [comment]
Un point nous échappe dans l'API et les classes user et client.
Que vont contenir concrètement ces 2 classes ?
Par exemple dans le cas du guichet adresse qui gère aussi bien des mairies, des postiers et des collecteurs IGN, nous pensions que le user était le guichet et que les clients étaient les mairies, postiers et collecteurs ? 
Ceci permettrait de stocker l'origine détaillé des mises à jour effectuées par le guichet. Ceci serait transparent pour l'utilisateur du guichet et gérer par la brique entre le guichet et l'API BAN.
Et de plus c'est conforme au scope qui sont porté par les clients.

On peut prendre d'autres cas concrets : que contiendront les classes user et client dans le cas du synchronisateur IGN -> BAN ? Synchronisateur Poste -> BAN ? Applicatif de mise à jour BAN de Rennes métropole ?

D'autre part, d'après le modèle actuel, un user est plus générique qu'un client et un client pointe vers un user.
Donc si le guichet adresse est dans la table client. Que contient user ?

**Comment by yohanboniface** [comment]
En gros, `User` est un humain responsable et point de contact du `Client`.

On aurait pu se passer de `User` à ce point, mais c'est une contrainte de la lib Oauth2 utilisée, et c'est donc plus simple de d'y conformer.

L'identité des utilisateurs finaux sont dans `Session` (email ou IP).

L'API n'a pas vocation à gérer les utilisateurs finaux, pour rester simple, pour permettre aux différents service d'implémenter les propriétés qu'ils veulent sur leurs utilisateurs, selon leurs métiers, pour ne pas avoir à gérer les passwords perdus, les changements d'email et tout ce workflow qui n'intéresse pas directement l'API de gestion.

On peut en parler demain en réu par oral. :)

**Comment by odorie** [comment]
Effectivement un petit point oral serait le bienvenu pour bien se caler :)
Pourrait-on profiter de la BAN Team de mardi 23/05 à 10 h par exemple ?
Si tu n'es pas dispo, on peut aussi t'appeler aujourd'hui ou demain

**Comment by yohanboniface** [comment]
Je suis a priori dispo mardi prochain, mais l'un n'empêche pas l'autre, on peut aussi s'appeler pour démêler des points particuliers quand il y a besoin ;)
A vot' dispo en tout cas :)
