### ISSUE TITLE
Cas des adresses de voies ayant plusieurs code postaux

### ISSUE THREAD

**Issue by yohanboniface** [BaseAdresseNationale/api-gestion#41]
C'est un des retours de l'OpenLab: les utilisateurs cherchent "hexacle" et ne connaissent apparemment pas "cea".

Note:  on peut aussi en profiter pour avoir un nom moins cryptique, et renommer en "laposte_id" par exemple, et compter sur la documentation pour rendre ça clair à ceux qui cherchent "hexacle".

cc @Apside-bdx-BBO @christopheprudent

**Comment by Apside-bdx-BBO** [comment]
Je ne voit pas de problemes à ce que se soit "laposte_id" ou "laposte" au même titre que "insee" ou "insee_id". 
C'est plus parlant que "hexacle" qui est le format du fichier fourni aux utilisateurs.

**Comment by MaelREBOUX** [comment]
+1

Il y a plein de codes INSEE. En collectivité le code INSEE communal se retrouve codé fréquemment en "insee_comm" ou "comm_insee".

**Comment by yohanboniface** [comment]
> +1

+1 pour laposte, lasposte_id ou hexacle? :)

> Il y a plein de codes INSEE. En collectivité le code INSEE communal se retrouve codé fréquemment en "insee_comm" ou "comm_insee".

Oui, mais quand il s'agit d'un attribut du model Municipality, je pense que c'est clair qu'il s'agit du code INSEE pour cet objet, de même ici pour "laposte" ou ce qu'on choisira :)

**Comment by christopheprudent** [comment]
ok pour laposte, laposte_id et un peu de documentation pour faire le lien avec la CEA (code étendu de l'Adresse) fourni dans le fichier HEXACLE, pour les voies et numéros

à nouveau une remarque des cardinalités par contre
relation 1-1 pour un numéro
relation 1-n pour une voie, qui possède donc autant de CEA que de CP associé

**Comment by yohanboniface** [comment]
Humm, en l'état, seul HouseNumber a un CEA. Est-ce qu'il faut en ajouter un sur la voie aussi?

**Comment by christopheprudent** [comment]
je pensais que l'entité HouseNumber, qui porte le lien vers ZipCode, pouvait aussi être renseigné pour la voie (avec number à null, 0) ?
sinon, en effet, il manque quelque chose grr...
mais l'entité Position (X,Y) est également liée à HouseNumber, sinon pas de localisation non plus pour une voie ?

**Comment by yohanboniface** [comment]
> je pensais que l'entité HouseNumber, qui porte le lien vers ZipCode, pouvait aussi être renseigné pour la voie (avec number à null, 0) ?

Oui, c'est bien le cas :)
Mais ça résout pas le cas d'une voie associée à plusieurs codes postaux: en l'état, un seul "housenumber" sera créé, et donc avec un seul CEA.

**Comment by christopheprudent** [comment]
ok, je n'avais pas vu comme toi alors:

il peut y avoir aussi plusieurs occurences dans HouseNumber pour une même voie (number non renseigné), avec pour différences le lien zipcode_id et donc aussi le CEA associé, non ?

**Comment by yohanboniface** [comment]
> il peut y avoir aussi plusieurs occurences dans HouseNumber pour une même voie (number non renseigné), avec pour différences le lien zipcode_id et donc aussi le CEA associé, non ?

En l'état, non, ça va pas passer les contraintes. Mais par ailleurs je me demande s'il faut aller dans cette direction, dupliquer les housenumbers parce qu'on a besoin de plusieurs CEA pour une même voie me semble un contournement du modèle actuel pour des besoins métier La Poste.
Je pense qu'il faut faut mouliner ça un peu plus.
Peut-être aller dans la direction d'une relation multiple entre housenumber et postcode et déplacer la CEA dans la relation entre housenumber et postcode?

**Comment by christopheprudent** [comment]
et comment traites tu le cas d'une voie non numérotée sur 2 CP, avec un exemple ci-dessous ?
Voie scindée non numérotée (sur commune pluri-CP)
	La Bolliaz, 01200 Chezery Forens
	La Bolliaz, 01410 Chezery Forens

ce cas existe dans notre référentiel
je l'ai extrait de la liste d'adresses type, envoyée ce matin par mail (sur la boîte fonctionnelle ld-sna-ban@laposte.fr)

**Comment by Apside-bdx-BBO** [comment]
Au risque de chambouler le mcd, pourquoi ne pas changer la table PostalCode afin qu'elle porte : 
-id (identifiant technique)
-PostalCode 
-housenumber_id
-Laposte_id (cea) (nullable  et fiabilisé par Laposte si renseigné)
Et la relation avec la table housnumber serait de type OneToMany (le hn à 0 ou 'null' aurait plusieurs codes postaux).

Cette modification répond aux exigences typiquement postales. Une « adresse » avec un code postal a un cea et LaPoste fiabilise cette relation. 
Cela nous permettrait de supprimer la table 'municipality_postalcode_through' liée à une municipalité car on pourrait, à terme, trouver la municipalité dont dépend une voie (ou autre...)

**Comment by yohanboniface** [comment]
>  voir page Wiki : https://github.com/etalab/ban/wiki/liste-d%27adresses-type

Excellent! Pour inspiration, https://lite6.framapad.org/p/horreurs_adresses à réintégrer peut-être?

> Au risque de chambouler le mcd, pourquoi ne pas changer la table PostalCode afin qu'elle porte :
> -PostalCode

Humm, cela dupliquerait le code dans autant de rows qu'il y a de housenumbers, non?

**Comment by Apside-bdx-BBO** [comment]
>Humm, cela dupliquerait le code dans autant de rows qu'il y a de housenumbers, non?

humm voui
A ce moment on enlève l'unicité sur 'number' et 'ordinal' porté par le cia. Dans ce cas on peut ajouter  le cp dans le cia pour le rendre unique.
A ce moment on peut gerer le cas 5 en laissant les tables existantes.
Le model repond au cas 3 si le fantoir existe et est dans le cia.

**Comment by yohanboniface** [comment]
Renommé cea en laposte (je crois qu'on est d'accord là-dessus), et renommé ce ticket en "Cas des adresses de voies ayant plusieurs codes postaux", parce qu'il me semble que c'est le sujet important qui ressort.

**Comment by yohanboniface** [comment]
Compte tenu de #65, #66, #67, je vois seulement deux options à l'heure actuelle:

- une crade, mais qui garde une modélisation simple: dupliquer tous les `housenumber` concernés (un pour chaque CP)
- une plus propre, mais qui complique la modélisation, et empêche plus ou moins d'utiliser le cea comme un "identifier" (au même titre que insee pour commune, fantoir pour rue, etc.): faire une relation many to many entre `housenumber` et `postcode`, et faisant de la `cea` une propriété de cette relation.

**Comment by christopheprudent** [comment]
d'accord avec la solution propre, sachant aussi que cet identifiant LAPOSTE (CEA) est contraint par le CP, à tous les niveaux d'adresse où ce lien est multiple
* commune ou quartier
* voie

seulement unique pour un numéro, en tout cas en interne! pour nous, sur le contre-exemple cité (5 ROUTE DE POUILLY), nous n'avons qu'un seul numéro déclaré!

**Comment by ebuard** [comment]
Quelle solution a été choisie au final? Ce ticket est-il toujours d'actualité ou a t'il été résolu?
