### ISSUE TITLE
[MCD] renommer HouseNumber en Address

### ISSUE THREAD

**Issue by MaelREBOUX** [BaseAdresseNationale/api-gestion#42]
Bonjour,

J'ai un vrai problème avec le terme "HouseNumber".

Une adresse / un numéro d'adresse peut en effet être attribué à bien d'autre chose qu'une maison d'habitation. Je le pensais avant l'open lab du 15/12 et les discussions qui ont eu lieu m'ont renforcé dans ma position.
Je viens de relire la spécification de données INSPIRE et je propose d'adopter le terme "Adress" qui est bien plus souple et générique et qui reflètera mieux les données disponibles dans la BAN.

Je met ici en pj l'analyse de l'AITF de 2011 sur la version 2.0 produite pour l'appel à commentaires. Les lecteurs retrouveront certains concepts.

[aux admins : impossible de téléverser un PDF malgré que ce soit indiqué comme format autorisé. taille = 424 ko]

**Comment by yohanboniface** [comment]
Oui, c'est une discussion qu'on a eue, cf notamment https://github.com/etalab/ban/issues/15#issuecomment-159269859

J'étais pas très chaud pour Address perso, parce qu'il me semble que l'adresse c'est la concaténation finale de plusieurs tables, mais si INSPIRE utilise ça, ça fait un argument de plus pour "Address".

**Comment by MaelREBOUX** [comment]
Bon : docx ça passe mais pas PDF :(

[A-I.5-Rapportage sur data spec Adresses.docx](https://github.com/etalab/ban/files/65202/A-I.5-Rapportage.sur.data.spec.Adresses.docx)

**Comment by MaelREBOUX** [comment]
> J'étais pas très chaud pour Address perso, parce qu'il me semble que l'adresse c'est la concaténation finale de plusieurs tables, mais si INSPIRE utilise ça, ça fait un argument de plus pour "Address".

C'est exactement ça pour INSPIRE aussi. Une Adress se décompose en AdressComponent. Sachant que chaque composant est essentiellement une chaîne de caractères pour laquelle on indique qu'elle est son niveau / son grain de description.
Il faut absolument s'en INSPIRé...

**Comment by MaelREBOUX** [comment]
**AdressNumber** c'est pas non plus hors sol.

**Comment by yohanboniface** [comment]
Oui (mais avec deux "d" alors, *AddressNumber*).
Bon, là on nous objectera que le number est optionnel, vu qu'on aura un point adresse y compris pour, par exemple, une rue, et dans ce cas il n'y a pas de "number" (bien sûr cette objection s'adresse tout aussi bien à "HouseNumber").

**Comment by MaelREBOUX** [comment]
oui : bien vu. **Address** reste plus cohérent alors.

**Comment by yohanboniface** [comment]
Pourquoi pas "Location"?
Idéalement, j'aimerais éviter "Address" tout court, parce que comme discuté l'adresse c'est *plutôt* la concaténation de tous les éléments constituants.

**Comment by MaelREBOUX** [comment]
Trop vague. Ou alors **Address Location** ?
Schant que on n'aura pas forcément de XY...

**Comment by yohanboniface** [comment]
AddressPoint? :)
(Comme on dirait "point adresse".)

**Comment by yohanboniface** [comment]
Sinon "Place", tout simplement?

**Comment by yohanboniface** [comment]
Autre suggestion, après un brainstorming avec @cquest et le MCD inspire sous les yeux (page 38): "Locator"

**Comment by ebuard** [comment]
Je suis plutôt de l'avis de Maël: il faudrait suivre les directives inspire....

**Comment by yohanboniface** [comment]
> Je suis plutôt de l'avis de Maël: il faudrait suivre les directives inspire....

Ce qui donne quoi concrètement dans le cas présent? :)

**Comment by ebuard** [comment]
Adress ou AdressName?

**Comment by yohanboniface** [comment]
> Adress

Perso, je suis réticent à l'idée d'utiliser "address", parce que le terme est trop générique, et à mon sens est plutôt la concaténation finale des différents éléments de la BAN, dont le "HouseNumber" (qu'on chercher à renommer, donc).

> AdressName

Ça ne me semble pas un "name". :/

**Comment by MaelREBOUX** [comment]
Selon INSPIRE je pense que l'on oscille ici entre les types **Address** et **AddressLocator** (figure 2 p. 24)

**Comment by yohanboniface** [comment]
J'aimerais bien avancer sur ce point, HouseNumber est vraiment un mauvais nom.

Les candidats sont:
- Address
- AddressPoint
- AddressLocator
- AddressName
- Locator
- Place

Personnellement, je préfère éviter `Address`, qui est à mon sens trop générique. Et par ailleurs je préférerais ne pas namespacer avec `Address`, parce que sinon il faut le faire partout pour être cohérent. Compte tenu de ces deux points, et en relisant le fil de discussion, il me semble que le meilleur candidat est **Locator**. Des avis contraires?

**Comment by alahoule** [comment]
Pas forcément un avis contraire mais si tu ne namespaces pas tout cela signifie que le préfixe 'address' est induit sur chacun des termes. On doit donc les choisir en tenant compte de ce point.

Il n'y a pas de risques de méprises sur le sens de `Locator `avec `Position`?
Je préfère `Place` dans son acceptation anglaise. Uniquement le risque de confusion française qui me gêne.

**Comment by laurentlabrunie** [comment]
Etant donné que j'avais visualisé ça plus comme un emplacement (défini éventuellement par son numéro, son extension, son nom de rue,... etc), le terme "place" me convient... voire "site" si on veut éviter la confusion.

**Comment by christopheprudent** [comment]
le but ici est bien de renommer HouseNumber (mais pas son périmètre fonctionnel): toujours l'entité de gestion des numéros dans la voie (avec astuce éventuelle du number à NULL pour désigner la voie elle-même, si non numérotée)

alors un autre nommage proposé, désolé
d'accord avec @yohanboniface pour ne pas utiliser Address, qui en effet englobe tous les éléments de l'adresse du lieu (CP, commune, voie, numéro, et/ou complément d'adresse)

pourquoi pas tout simplement Number (ou PublicNumber), pour désigner ces numéros, qui sont assignés par la commune (d'où le préfixe Public) ?

**Comment by yohanboniface** [comment]
> pourquoi pas tout simplement Number (ou PublicNumber), pour désigner ces numéros, qui sont assignés par la commune (d'où le préfixe Public) ?

Parce que justement, c'est pas toujours un *number* (cf quand il n'y a pas de number, pour désigner un point adresse lié directement au group parent) ;)

**Comment by christopheprudent** [comment]
ok
alors plutôt d'accord avec @laurentlabrunie , pour en français : _emplacement_, _lieu_, _endroit_
soit en anglais: _place_, _spot_

**Comment by ebuard** [comment]
Pour moi, Place est ambigüe à cause des places et donc des lieux-dits.

Je pense toujours qu'on oscille entre Address et AddressLocator. Reprenons la liste des noms proposés:

- Address est trop générique pour toi, yohan.

- AddressPoint laisse entendre une géométrie (alors que c'est une classe sans géométrie)

- Locator et AddressLocator reprennent clairement les termes Inspire, sauf que l'implémentation diffère de celle d'Inspire. Ce sont donc des faux-amis.

- AddressName laisse entendre seulement un libellé, alors que notre classe est aussi une classe logique.

En conclusion: oui pour Locator ou AddressLocator, mais il faudrait faire évoluer le schéma pour se rapprocher de celui d'Inspire, en particulier gérer ici les niveaux hiérarchiques d'adresses (adresses filles/ adresses parentes). Ou Address mais c'est très générique.

**Comment by alahoule** [comment]
L’ambiguïté du `place` comme je l'indique précédemment est neutralisée par le fait que tout le modèle est en anglais. Quelqu'un connaît un synonyme de **Place** en anglais ?

**Comment by ebuard** [comment]
Et j'ai une proposition: si on traduisait tous les noms des classes et des champs? Ceci permettrait d'éviter toute confusion avec Inspire.
L'inconvénient, c'est qu'il faudra gérer des accents, comme dans tous les noms français. 
Les avantages, c'est d'abord qu'on se conforme à la loi (Toubon en l'occurence): le français est censé être la langue des échanges dans le travail, des services publics et la documentation d'un produit, puis qu'on facilite la compréhension du modèle pour des contributeurs français.

**Comment by cquest** [comment]
Je propose **AddressNumber**

Dans HouseNumber c'est house qui me déplait, pas Number. Ok number peut être nul, mais l'essentiel est bien de fournir un numéro dans un groupe. L'indice de répétition est lié au numéro.

On n'a pas à coller à 100% à la terminologie INSPIRE, c'est à l'export INSPIRE qui faudra rentrer dans le moule, pas dans la façon de gérer les données.

**Comment by yohanboniface** [comment]
> Je propose AddressNumber

Si on va par là, il faut faire AddressGroup, AddressPosition… :s

**Comment by ebuard** [comment]
Le modèle a été validé par la communauté technique à l'été 2016 avec les noms des tables initiaux.
