### ISSUE TITLE
Ajouter les IRIS?

### ISSUE THREAD

**Issue by yohanboniface** [BaseAdresseNationale/api-gestion#48]
Citation de #43 :

> L'INSEE ne les maintient pas car refuse actuellement (presque ?) tous les redécoupages nécessaires pour tenir compte des évolutions urbaines. Dans plusieurs métropoles nous avons des cas de zones IRIS coupant des immeubles récents ou agrégeant trop de population / logements par rapport à ce que cela devrait être.
> Si nous disposions d'un autre maillage infra communal (carreaux 200m ? mais ils bougent) une bonne part des CT l'utiliseraient déjà. Je déconseille déjà utilisation IRIS pour toute analyse sur notre territoire : trop grand et pas à jour (cf http://geobretagne.fr/geonetwork/apps/georchestra/?uuid=df789a3f-9980-4629-95be-50a8b04eac3c)

**Comment by MaelREBOUX** [comment]
Je pense que l'appariement IRIS <--> adresse devrait être du ressort d'un service web dédié. Si le besoin s'en fait réellement sentir.

Ce sont 2 données trop éloignées pour être stockées ensemble. Le découpage des IRIS se calant de préférence sur des linéaires de voies. Or les géométries de voies ne sont pas dans le périmètre de la BAN.

**Comment by yohanboniface** [comment]
> Je pense que l'appariement IRIS <--> adresse devrait être du ressort d'un service web dédié. Si le besoin s'en fait réellement sentir.

Ce sera dans tous les cas dans l'API carto je pense (cf https://github.com/sgmap/apicarto).

**Comment by cquest** [comment]
A mon avis, ce n'est pas un problème de géométrie.
L'appartenance d'une adresse à un IRIS est du même ordre que le lien adresse / code Postal.
C'est à regrouper via nos "districts"... si l'INSEE se charge de cela bien sûr tout comme La Poste le fera pour les codes postaux.

**Comment by ebuard** [comment]
Les IRIS ne sont pas dans le modèle actuellement.
