### ISSUE TITLE
Liste de valeurs admises pour "Position.kind"

### ISSUE THREAD

**Issue by yohanboniface** [BaseAdresseNationale/api-gestion#51]
On a parlé d'utiliser la terminologie INSPIRE: http://inspire.ec.europa.eu/documents/Data_Specifications/INSPIRE_DataSpecification_AD_v3.1.pdf

**Comment by MaelREBOUX** [comment]
oui : je suis en train de faire valider une liste adaptée par le groupe de travail AITF.
La période de congés implique d'attendre qqs jours pour un retour.

**Comment by MaelREBOUX** [comment]
Document en relecture finale.

Une question en relisant la dernière version de https://github.com/etalab/ban/wiki/MCD-of-BAN 

Pour **PositionType**, merci de donner une définition pour les attributs car c'est pas clair :
- name
- description
- referent

**Comment by MaelREBOUX** [comment]
Voici la liste de valeurs proposée par l'AITF en se fondant sur les valeurs INSPIRE de la spécification de données "Addresses" :

**délivrance postale**
Identifie un point de délivrance postale (boîte aux lettres)

**entrée**
Identifie l’entrée principale d’un bâtiment ou un portail.

**bâtiment**
Identifie un bâtiment ou une partie de bâtiment.

**cage d’escalier**
identifie une cage d’escalier, en temps normal à l’intérieur d’un bâtiment.

**logement**
identifie un logement ou une pièce à l’intérieur d’un bâtiment.

**parcelle**
Identifie une parcelle cadastrale.

**segment**
Position dérivée du segment de la voie de rattachement.

**service technique**
Identifie un point d’accès technique (ex : local disposant d’organe de coupure eau, électricité, gaz, etc)

Pour plus de précision, lire : https://framadrop.org/r/YY9BG7Z_y5#UMZ/TUDhbporMvjwAZu3Vk/IAz6H7lXeyRjFy7Zcmns

**Comment by christopheprudent** [comment]
> En l'état, il me semble comprendre que tous les cas cités ici rentrent dans la modélisation actuelle (aussi bien que dans les deux autres en cours d'étude): ou bien en tant que District (type 3 dans ton tableau), ou bien en tant que position (type 1 et 2 dans ton tableau).
Est-ce qu'on a d'autres points à checker?
concernant la norme adresse, voici les étapes réalisées pour respecter la taille du libellé (selon la norme utilisée, de 32 ou 38 caractères)
On est bien d'accord que dans la BAN on aura que les libellés complets?

je pense que ça colle aussi, attention toutefois, le type 3 peut correspondre en fait aux 2 cas soumis (une résidence par exemple, qui comme dans l'exemple de @MaelREBOUX précise l'adresse du numéro 15; mais aussi une résidence dans laquelle sont dénommées d'autres voies)

par contre, aujourd'hui (je me renseigne en interne), il me semble possèder que ces libellés normés

**Comment by yohanboniface** [comment]
@MaelREBOUX est-ce que tu as la liste des libellés en anglais par hasard?

**Comment by yohanboniface** [comment]
OK, vus dans ton document sur #75.

**Comment by yohanboniface** [comment]
@MaelREBOUX petite question: pourquoi tu n'as pas gardé "ThoroughfareAccess"?

**Comment by MaelREBOUX** [comment]
parce que une adresse qui représente une voie d'accès on pense que c'est pas très représentatif des données adresses gérées en France. On préférera indiquer "entrée" (entrance).

**Comment by ebuard** [comment]
Et pareil pour "Address Area": pourquoi ne pas les garder?

**Comment by ebuard** [comment]
Pour fournir une documentation précise aux utilisateurs, je propose de compléter ces positionnements en:
**délivrance postale**
Identifie un point de délivrance postale (boîte aux lettres)

**segment**
Position dérivée du segment de la voie de rattachement.

**service technique**
Identifie un point d’accès technique (ex : local disposant d’organe de coupure eau, électricité, gaz, etc)

**cage d’escalier**
identifie une cage d’escalier, en temps normal à l’intérieur d’un bâtiment.

**logement**
identifie un logement ou une pièce à l’intérieur d’un bâtiment.

**entrée**
Identifie l’entrée principale d’une parcelle avec ou sans portail ou d'un batiment. Avec positioning = "projection", cette valeur est ce point projetée sur la voie.
_Question: "entrée de batiment", on le laisse dans "entrée" ou on le mets dans "batiment"? Pour Parcel, je pense "entrée" tout court, et non "parcelle". Doit-on faire la même chose?_

**bâtiment**
Identifie un point particulier (centroïde) ou non d'un bâtiment ou une partie de bâtiment. Avec positioning = "projection", cette valeur est ce point projetée sur la voie.

**parcelle**
Identifie le centroïde d'une parcelle cadastrale. Avec positioning = "projection", cette valeur est le centroïde de la parcelle projetée sur la voie.

Pour l'IGN, il faudrait aussi avoir **Address area**: identifie le centroïde d'un lieu auquel l'adresse est rattachée, comme un lieu-dit, un quartier, un ensemble résidentiel ou une zone industrielle.

Qu'en pensez-vous?

Il faudrait aussi écrire des cas d'usage pour les utilisateurs pour classer ses adresses dans les bonnes catégories de Kind et Positioning.

**Comment by odorie** [comment]
Elodie, à ta demande, je réactive ce ticket pour que tu puisses apporter des précisions sur certaines valeurs.
Par contre, je trouve les formulations de Maël plus claires (et plus proches d'INSPIRE) et il ne faudrait pas parler du champ positioning ici.  Donc ma proposition : revenir au formulation de Maël et préciser la valeur Entrance qui est encore ambigu : par exemple en faisant quelques dessins.

**Comment by odorie** [comment]
Et aussi ajouter la valeur "Address area" (valeur inspire) pour pouvoir caractériser certaines positions géométriques IGN (placées sur un lieu-dit). cf #179

**Comment by ebuard** [comment]
Merci pour ta réaction, @odorie !

Tu as raison: il faut réfléchir sur des petits schémas.
Pour faire avancer la discussion sur Entrance, j'ai repris simplement l'image de Maël, en rajoutant trois points d'entrées possibles pour le 15 rue des mimosas, en rouge dans l'image: 1, 2 et 3
![entree](https://cloud.githubusercontent.com/assets/15909440/19081429/89d26b02-8a5a-11e6-8c86-507d80a794ee.png)

Est-ce que les positions avec Kind = Entrance sont :
- le point 1 seulement (parce qu'il n'y a qu'une seule Entrance par source et le point 1 semble être l'entrée principale)
- ou les autres points seulement (ce ne sont pas les entrées principales, mais les entrées des bâtiments)
- les points 1, 2 et 3 en créant 3 positions entrée -> doit-on créer une hiérarchie de positions pour ces cas?,
- les points 1 et 2 (parce que le point 3 correspond à un bâtiment secondaire) en créant 2 positions entrée -> idem?.
?

Il s'agit d'un premier exemple illustré. Je réfléchis à d'autres cas dans le but d'expliquer les types d'entrées aux utilisateurs.

**Comment by ebuard** [comment]
J'ai réfléchi à un autre cas d'usage très simple.
Prenons 1 parcelle, contenant 3 bâtiments, d'accès piétons.
![exempleskind2](https://cloud.githubusercontent.com/assets/15909440/19114664/373f994a-8b0f-11e6-9ace-64643467afd1.jpg)
Comment qualifie t'on les types d'entrées des positions marquées de 1 à 4?
1: on est tous d'accord que Kind = Entrance? On sous-entend "entrée de parcelle" ou "entrée principale".
2: Kind= Entrance ou Building? On sous-entend "entrée de bâtiment principal".
3: Kind = Entrance ou Building ? On sous-entend "entrée de bâtiment secondaire".
4: Kind = Entrance ou Building ? On sous-entend "entrée de bâtiment secondaire".
Inspire ne nous aide pas du tout pour les cas ambigus.

Et je me demande: si toutes les positions sont Kind = Entrance, comment les utilisateurs font pour distinguer les entrées principales de parcelles (c'est à dire sélectionner les positions 1 dans la figure)?

**Comment by christopheprudent** [comment]
plutôt d'avis alors de réserver *Entrance* à l'entrée principale (accès) et *Building* à l'entrée d'un bâtiment, soit ici:
1 = *Entrance*, les autres avec *Building*

**Comment by odorie** [comment]
Je me pose des questions sur cette règle mais peut-être que j'ai mal compris : 
Si on l'applique, un certain nombre d'immeubles en ville, qui donne directement sur la rue, n'auront pas de kind "entrance" ?
De plus on mélange alors dans la notion valeur "Building" une position placée n'importe où dans le bâtiment avec une position placée à l'entrée principale ou de secours.

**Comment by cquest** [comment]
"entrance" pour moi c'est en général le point de passage entre domaine public et domaine privé
"building" permet de détailler un peu plus et fait référence à un bâtiment ou son entrée si ça ne donne pas directement sur le domaine public

après il faudrait effectivement pourvoir détailler entre position du bâtiment (centroid ?) et entrée du bâtiment...
c'est quelque chose que je verrai plutôt en attributes car on peut aller loin comme ça.

Sur OSM on a souvent des tags plus ou moins hiérarchique qui permettent de rentrer dans les détails plutôt que d'avoir pour le tag de premier niveau un trop grand nombre de valeurs.

**Comment by MaelREBOUX** [comment]
En fait, ce qui gêne @ebuard c'est le "ou" dans  _Identifie l’entrée principale d’un bâtiment **OU** un portail_

Je crois que ce côté flou existe déjà dans la spec INSPIRE. On pourrait effectivement limiter la définition à celle proposée par @christopheprudent mais en musclant la définition.

Par contre @cquest , il ne faut PAS aller sur les histoires de domanialité : c'est trop casse-gueule. Préférer une définition passe-partout qui permet de comprend quand on doit mettre "entrance" et quand on doit préférer "building".


**entrée**
Identifie le point d'accès principal à une enceinte ouverte ou fermée, un groupe de bâtiments, un terrain (autre qu'une parcelle cadastrale). Typiquement : un portail d'accès.

**Comment by ebuard** [comment]
Donc, si je résume, on fait ça: 
![exempleskind2_specifie](https://cloud.githubusercontent.com/assets/15909440/19239508/a31c5f68-8f06-11e6-9a40-a14396be3f95.jpg)
1 entrée + 3 buildings à cette adresse
Ça va?

Ce qui me fait étendre ce cas d'usage: que se passe t'il s'il y a deux entrées à la parcelle? Tout le monde est d'accord pour le fait de conserver 2 entrées? On peut imaginer une voie piétonne et une voie voiture. Sur cette figure, j'ai rajouté un point d'entrée, mais aussi un point building et éventuellement 1 autre point dans un building, de type building ou staircase.
![exempleskind3_specifie](https://cloud.githubusercontent.com/assets/15909440/19239582/fa8c74e0-8f06-11e6-83c6-ed4bd6712795.jpg)


Je trouve ça mieux cette définition d'entrée. Merci de vos réactions!

**Comment by ebuard** [comment]
Tout le monde est d'accord sur les différentes valeurs de kind. Adress area a été ajoutée. Des consignes ont été écrites dans ce ticket et dans le wiki. Elles seront surement à affiner dans le futur par l'expérience après l'ouverture de la BAN et avec les retours des utilisateurs.
