### ISSUE TITLE
Fonctionnalités transactionnelles d’écriture par bloc de données

### ISSUE THREAD

**Issue by ebuard** [BaseAdresseNationale/api-gestion#59]
Actuellement dans l’API, les créations/modifications d’objets sont à envoyer une par une. En cas de création de voie et d’adresses liées, l’utilisateur de l’API devra veiller à la bonne exécution des créations. En cas de souci (coupure réseau ou autres) au milieu de l’opération, l’utilisateur devra être en mesure de reprendre uniquement les créations non faites. Il pourrait être intéressant de lui proposer un mode transactionnel où il pousserait ces créations/modifications d’un bloc (et donc soit toutes passent, soit aucune).

**Comment by MaelREBOUX** [comment]
C'est un changeset comme dans OSM en sorte ?

**Comment by ebuard** [comment]
Je ne sais pas, mais c'est juste une idée, à garder dans le coin de la tête ;-)

**Comment by cquest** [comment]
C'est délicat avec la gestion des conflits de version sur les objets.
Que se passe-t-il lorsque deux transactions en cours modifient les mêmes objets mais dans un ordre différent ?

**Comment by ebuard** [comment]
On ferme ce ticket. On le rouvrira si jamais le besoin se précise.
