### ISSUE TITLE
fusion de communes

### ISSUE THREAD

**Issue by christopheprudent** [BaseAdresseNationale/api-gestion#62]
description du cas d'usage d'une fusion de communes
1. partie Commune
   - ajouter les anciennes communes dans l'entité **District**, en mémorisant leur code INSEE 
   - effacer les anciennes communes de l'entité **Municipality**
   - modifier éventuellement le libellé de la commune résultante, en cas de renommage
2. partie Voie
   - mettre à jour le lien d'attachament des voies (entité **Street**) vers la nouvelle commune (colonne _municipality_id_)
   - mettre à jour le lien d'attachament des voies (entité **Street**) vers le "quartier" (colonne _district_id_), pour conserver l'ancien attachement, et pouvoir restituer l'adresse précise de ce lieu (avec ce libellé ancienne commune, écrit entre le libellé de voie et celui du code postal et commune), à conserver pour un éventuel retour en arrière (annulation de la fusion, cela arrive :cold_sweat:)

autre issue à venir pour détailler cette nouvelle entité **District**, en lien direct avec l'entité **Housenumber**...

**Comment by yohanboniface** [comment]
C'était référencé dans #18 mais je vais fermer là-bas plutôt et garder ici, la description est plus détaillée ;)

**Comment by yohanboniface** [comment]
Voir aussi #18, qui est le cas inverse.

**Comment by christopheprudent** [comment]
à étudier la fusion pour la gestion des voies, car 2 cas sont à distinguer:

1. voies en prolongement (ex: rue Vaugirard à Paris 6 et 15)
2. voies distinctes (ex: rue Kleber à Bordeaux)

pour la  cas 1, il s'avère peut-être nécessaire de "fusionner" ces 2 voies, pour n'en laisser qu'une (et gérer un lien pour associer l'autre sur celle-ci)

**Comment by odorie** [comment]
Suite à la réunion Ban Team du 27/09, je réveille ce ticket "dormant" pour continuer la discussion.
Cet outil de fusion est nécessaire pour l'initialisation de la BAN. Il sera aussi utile tout au long de la vie de la BAN pour assurer les fusions de commune à venir dans les prochaines années (outil pérenne).

En plus des spécifications fonctionnelles décrites par @christopheprudent, des questions se posent sur le développement de cet outil et de son articulation par rapport à l'API.

En réunion Ban Team, nous avons parlé d'un script (shell, python , perl ?) prenant en entrée :
- une liste d'arguments (insees avant, insee et nom de commune après ...?), 
- des données (insees et nouveaux codes postaux, redirection des fantoirs ?)

Ce script préparerait et lancerait un ensemble de requêtes sur l'api ban pour réaliser la fusion de communes (création de la nouvelle commune, réaffectation des groupes, création des groupes secondaires ...)

Comment/ par qui cette commande doit-elle être appelée ?
- en ligne de commande sur le serveur ban par un administrateur de la ban ?
- via une nouvelle route de l'api avec des droits spécifiques ?
- depuis l'interface ban/monitoring d'administration ?

Qui lancera cette commande ? La personne en charge de l'administration ban ? Autre ?

**Comment by christopheprudent** [comment]
je pencherai plus sur une interface BAN d'admin en effet, avec des droits spécifiques

**Comment by cquest** [comment]
J'ajoute une 4ème option pour l'appel de ce script:

1. en ligne de commande sur le serveur ban par un administrateur de la ban ?
2. via une nouvelle route de l'api avec des droits spécifiques ?
3. depuis l'interface ban/monitoring d'administration ?
4. script externe passant par l'API

Les arguments minimum à passer au script: 
- code INSEE commune nouvelle (chef lieu)
- nom de la commune nouvelle
- codes INSEE des communes à fusionner

Les opérations à prévoir:
- création des groupes correspondant aux anciennes communes
- suppression des municipality qui disparaissent et création des redirections vers la nouvelle (à laquelle j'attribuerai un nouvel id BAN vu qu'on ne parle plus du même "objet" même si le code INSE est malheureusement recyclé)
- mise à jour de municipality_id sur les group
autre chose ?

Pour les droits, le script aura besoin d'un scope sur l'API lui permettant de modifier municipality, donc réservé par exemple à l'IGN.

Ensuite il y a 2 autres opérations à prévoir: l'une pour les changements postaux, l'autre pour les nouveaux FANTOIR
Ces scripts seront sûrement séparés vu qu'on les appliquera sûrement potentiellement plus tard (surtout pour FANTOIR) et n'auront pas besoin du scope sur municipality.

**Comment by ebuard** [comment]
Spécifications de l'outil pour la fusion des communes d'insee A+B+C --> A:
l'outil ne fait que la fusion administrative.
Il gère les codes postaux de façon générique --> les nouveaux libellés d'acheminement seront à mettre à jour ensuite par la Poste via l'API ou par un autre script
Il conserve les codes fantoirs --> les nouveaux codes fantoirs seront à mettre à jour ensuite  via l'API ou par un autre script
Il ne gère pas les fusions de voie (cas de voies frontières ou prolongement)
Le script est une commande python ( dans une seule transaction pour conserver une base cohérente).
En argument de la commande : 
- insee de la commune maîtresse
- nom de la nouvelle commune
- libellé d'acheminement de la nouvelle commune
- insee des autres communes


**Municipality**
Les communes B et C sont détruites (soft delete). On met des redirections vers la commune A (à faire pour les identifiants et les insee).
Si la commune A (commune maitresse) garde le même nom, on modifie quand même cette commune pour garder trace de la fusion (on mettra dans attribut "Fusion de commune").

**PostCode**
Le modèle doit évoluer : ajout du champ ligne 5 --> proposition subname
Les codes postaux sont conservés. Les anciens libellés d'acheminement sont mis en subname si le subname est vide (cas Orvanne). Le nouveau libellé d'acheminement sera indiqué en argument de la commande et fourni par la poste

**Group**
Pour les anciennes communes, on créé des groupes avec l'ancien code insee en attributs.
Les groupes des anciennes communes sont à faire pointer sur la nouvelle commune.
Si cette opération met en place des groupes de même nom dans la commune fusionnée, on met un message dans le log.

**hn** 
On créé un hn null pour les nouveaux groupes secondaires.
On ajoute ces groupes "anciennes communes" en groupes secondaires (ancestors) de tous les hn (y compris les hn null)

**Comment by yohanboniface** [comment]
@christopheprudent est-ce que tu pourrais nous détailler l'état des codes-postaux chez vous (ligne 5 et 6 notamment) pour quelques-unes des fusions de commune récente?

**Comment by odorie** [comment]
@gschittek , il me semblait que la commande fusion était terminée et mergée ?

**Comment by gschittek** [comment]
Terminée mais pas mergée, elle est encore sur la branch merge_mun

**Comment by yohanboniface** [comment]
Nope: #245 
Quelques finitions manquent, je pense m'en charger dans les jours à venir, une affaire de deux/trois heures.
