### ISSUE TITLE
Dépendance au FANTOIR

### ISSUE THREAD

**Issue by yohanboniface** [BaseAdresseNationale/api-gestion#64]
Il y a je pense un remue-méninges à faire sur le FANTOIR. En l'état la modélisation de la BAN dépend très fortement du FANTOIR:
- colonne unique sur les table Street et Locality permettant de luter en partie contre les doublons
- dépendance de la [CIA](https://github.com/etalab/cle-interoperabilite-adresse) au FANTOIR

Or nous n'avons pas la main sur la création de ces codes,  et on sait qu'ils ne sont pas créés dès l'enregistrement d'une nouvelle voie.

Il me semble même que, dans un monde idéal, c'est la BAN qui devrait être responsable de générer un tel identifiant référent. Mais, même dans un tel cas, il serait certainement judicieux de garder le FANTOIR stricto sensu comme identifiant _possible_ (mais non obligatoire).

**Comment by MaelREBOUX** [comment]
Le Fantoir doit dors-et-déjà être considéré comme un identifiant secondaire.

Nous attendons tous un identifiant unique national (et pas communal) avec toutes les règles de bonne gestion inhérentes. L'API doit être considéré comme le guichet qui délivre ces identifiants uniques.

cf les propositions AITF : https://t.co/LNI01tp0cf

**Comment by yohanboniface** [comment]
> cf les propositions AITF : https://t.co/LNI01tp0cf

Je n'ai pas accès aux documents.

**Comment by MaelREBOUX** [comment]
https://framadrop.org/r/UNQL1b_8u8#pXGSZ7AD7/NVTOlkVGX7KpLIuHafXO+yUhJ41IXLhMs=

**Comment by yohanboniface** [comment]
Merci :)

**Comment by ebuard** [comment]
Nous pensons que cette dépendance n'existe plus. A confirmer.
