### ISSUE TITLE
géolocalisation, CP, CEA pour un Quartier

### ISSUE THREAD

**Issue by christopheprudent** [BaseAdresseNationale/api-gestion#67]
de même nature que les issues #65 et #66 

:information_source: à noter là aussi la contrainte du CP, qui génére un lien 1-n avec le CEA

ex: INSEE 98729 du **District** 'PAOPAO' de la commune 'MOOREA MAIAO' sur 2 CP
- CP= 98728, CEA= 9872922227
- CP= 98729, CEA= 987292222L

**Comment by yohanboniface** [comment]
A noter qu'en l'état, un housenumber doit être lié à une Street ou bien à une Locality. Donc il n'est pas possible d'avoir une housenumber seulement associé à un Disctrict (idem pour Municipality). C'est donc un point à traiter si on veut des points adresse pour les Disctrict et les Municipality.
