### ISSUE TITLE
Description des services via fichier WADL

### ISSUE THREAD

**Issue by MaelREBOUX** [BaseAdresseNationale/api-gestion#68]
Bonjour,

serait-il possible de générer / de disposer d'un fichier WADL qui décrive la capacité des services de l'API de gestion ?

Dans le monde OGC la méthode getCapabilities remplit cette tâche.
Offrir un WADL est, me semble-t-il, plus qu'une bonne pratique.

**Comment by cquest** [comment]
WADL ou WSDL ? ;)

WADL semble d'un usage moins standard que WSDL.
WDSL est une recommandation du W3C, quid de WADL ?

Tu connais des outils (utilisés) qui utilise ça ?

**Comment by cquest** [comment]
Plutôt partir sur https://github.com/OAI/OpenAPI-Specification

OpenAPI (ex swagger)

En plus là, il y a plein d'outils...

**Comment by MaelREBOUX** [comment]
J'ai essayé d'utiliser swagger l'année dernière pour http://rva.data.rennes-metropole.fr/documentation.php mais pas réussi. Je ne sais plus pourquoi mais un truc collait pas.

Espérons que la V 2.0 renommée sera plus facilement utilisable.

**Comment by ebuard** [comment]
Est-ce que SwaggerUI répond à cette problématique? Peut-on fermer ce ticket?
