### ISSUE TITLE
MCD: Historique dépilement d'adresses

### ISSUE THREAD

**Issue by ebuard** [BaseAdresseNationale/api-gestion#78]
Peut-on stocker dans la base l'historique de dépilement d'adresses effectué depuis 2015 sur les adresses par les collecteurs IGN?
Cela permettrait d'être plus précis directement... ou alors d'empêcher certaines modifications/suppressions parce qu'elles ont été contrôlées sur le terrain.

**Comment by cquest** [comment]
C'est le principe des certifications qui permettent de savoir qu'à un moment donné l'IGN met son coup de tampon sur une version donnée de la position d'une adresse et de mettre en attribut les metadonnées sur la précision géo ou autre.

**Comment by ebuard** [comment]
Oui, je comprends tout à fait les certifications d'adresses. Mais peut-on stocker les dépilements d'adresses déjà effectués? Autrement dit, peut-on afficher les certifications d'adresses déjà effectuées/ les adresses vérifiées, avant la création du modèle et d'API?
En métadonnées, on pourrait?

**Comment by cquest** [comment]
Ce n'est qu'un problème de timestamp il me semble, non ?
En fait, je ne saisis pas trop l'intérêt de conserver une données ancienne qui avait une moindre qualité que l'actuelle.
