### ISSUE TITLE
MCD: Liens d'appariement d'adresses?

### ISSUE THREAD

**Issue by ebuard** [BaseAdresseNationale/api-gestion#79]
Peut-on stocker dans la base les liens d'appariement (IGN et La Poste, mais aussi d'autres comme DGFIP, INSEE, communautés de communes....)qui existent entre adresses, de façon à créer une dépendance entre adresses et ainsi faciliter le contrôle des modifications : sémantiques, géographiques. En gros, il suffirait de réinspecter ce lien pour contrôler les modifications au lieu de repasser par les SI de l'IGN et de La Poste, donc on gagnerait du temps.
Difficultés: 
- mettre à jour ce lien à chaque nouvelle contribution.
- créer une hiérarchie d'adresses - ou au moins un lien entre adresses - dans le modèle.... à la manière d'Inspire?

**Comment by cquest** [comment]
On a déjà ce type de lien (housenumber / street, housenumber / locality, housenumber / postcode, housenumber / district)... on alors je n'ai pas compris de quoi il s'agissait.

**Comment by ebuard** [comment]
En fait, ce sera bien de stocker les relations entre adresses qui représentent la même adresse. Du coup, depuis le 15 février, il y a maintenant des liens de filiations entre adresses (sur HouseNumber ou Position), autrement dit il y a une adresse mère et des adresses filles. Il y a ainsi toujours un lien entre une adresse mère et une adresse fille. Doit-on quand même stocker des liens entre 2 adresses filles? C'est ce que j'appelle des liens d'appariement d'adresses.
Ceci faciliterait les validations, mais c'est peut-être inutile et chronophage.
