### ISSUE TITLE
format de stockage du FANTOIR et fusion de commune

### ISSUE THREAD

**Issue by yohanboniface** [BaseAdresseNationale/api-gestion#93]
Actuellement, on stocke le FANTOIR sous la forme `INSEEFANTOIR` (exemple `350010065`) pour avoir des valeurs uniques sur toute la table.
L'idée étant de pouvoir utiliser le FANTOIR comme identifier, donc pouvoir appeler l'API avec quelque chose genre: `/street/fantoir:350010065`.
Il faut prendre ça en compte quand on fait des fusions/scissions de communes.
Et en tâche de fond voir si on a pas une meilleure idée qui permettrait de stocker que le FANTOIR dans la colonne.

**Comment by cquest** [comment]
Il faut voir avec nos amis de la DGFiP pour récupérer les fichiers de correspondance lors de changement de codes FANTOIR (fusions de communes, mais aussi corrections à la DGFiP).
Ces données existent en interne comme cela a été confirmé en openlab et lors d'autres réunions.
Il faudra les conserver comme redirection, comme les changements de CEA ou de codes INSEE lors de fusions de communes...

**Comment by ebuard** [comment]
Reste t'il des choses à faire? Si oui, les préciser.

**Comment by gschittek** [comment]
script redirection des fantoirs fait
