### ISSUE TITLE
Champ "positioning"

### ISSUE THREAD

**Issue by yohanboniface** [BaseAdresseNationale/api-gestion#97]
Lors de notre atelier import, nous avons décidé d'ajouter un champ sur Position permettant de définir la méthode utilisée pour le positionnement.
Pour l'instant (sur la branche `remove-proxy`), je suis parti sur:
- nom du champ: `positioning`
- valeurs acceptées: `dgps` (differential gps), `gps`, `imagery`, `interpolation`, `projection`, `other`

Voir https://github.com/etalab/ban/commit/6a03232cef030e5dd266923a460bd4f513d2278b#diff-9f1e35a38252c8eed20fb8efd5813138R205

Merci de vos retours/propositions sur le nommage et les valeurs acceptées. :)

**Comment by MaelREBOUX** [comment]
Il faudrait les définitions pour se... positionner (!)

**Comment by yohanboniface** [comment]
dgps => gps différentiel
gps => gps
imagery => positionnement via imagerie satellite
interpolation => calcul par interpolation
projection => calcul par projection
other => autre

:)

**Comment by MaelREBOUX** [comment]
>  nous avons décidé

C'est qui le "nous" ?
Parce que là on ne sent pas franchement la concertation sur ce nouvel attribut qui n'est pas un poids plume...

**Comment by yohanboniface** [comment]
> C'est qui le "nous" ?

Les gens qui étaient présents lors de l'atelier en question.

Je signale que tu es présentement en train de répondre à un ticket ouvert sur le sujet, je crois que c'est justement ce qu'on appelle de la concertation. Donc plutôt que de râler, n'hésite pas donner ton avis argumenté, parce que ce ticket est là pour ça ;)

**Comment by MaelREBOUX** [comment]
Je râle pas mais c'est pas tjs facile de tout suivre à distance. Mets-toi à notre place.
Je suis favorable aux méthodes agiles mais sortir en avril cet attribut on trouve que c'est pas rien. 
On en déduit que le "nous" fait référence aux membres fondateurs. Tu confirmes ?

Sur la demande, les retours que j'ai sont que cet attribut n'est pas souvent géré voire pas du tout géré (pas assez de retours). 2 raisons semblent se dessiner. La première : dans une logique de mise à jour du référentiel, il semblerait que la saisie se fasse bcp sur fond de plan (cadastre ou plan de ville) ou orthohotographie. La deuxième : il n'y aurait pas de plus-value réelle à connaître cette info. 
Certifier l'existence de l'adresse et sa localisation : c'est déjà pas rien.

Pour rester constructif :
- rajouter "basemap" pour cadastre, plan de ville, etc
- rajouter "orthoimagery" : une ortho à 5 cm ne peut pas être comparée à une image satellite BING...
- rajouter "unknown"

**Comment by yohanboniface** [comment]
>  On en déduit que le "nous" fait référence aux membres fondateurs. Tu confirmes ?

yep ;)

>  La première : dans une logique de mise à jour du référentiel, il semblerait que la saisie se fasse bcp sur fond de plan (cadastre ou plan de ville) ou orthohotographie. 

On a une valeur pour ça: `imagery` :)

> il n'y aurait pas de plus-value réelle à connaître cette info.

Y a eu débat lors de l'atelier imports, spécifiquement sur s'il fallait ou non le mettre en colonne, ou bien le laisser dans `attributes`. Ce qui a décidé à en faire une colonne, c'est pour avoir une liste de valeurs contrôlées. Par définition, `attributes` a des valeurs libres.
Perso, j'ai pas d'avis tranché. Je pense que c'est une info intéressante, mais comme toujours je pense que les infos ne sont intéressantes que si elles son globalement uniformes sur la base et qu'elles sont maintenues.

> rajouter "basemap" pour cadastre, plan de ville, etc

C'est pas la même chose qu'`imagery`, ça?

> rajouter "unknown"

Et du coup j'enlèverais `other`, non?

Et… merci pour ce retour! :)

**Comment by MaelREBOUX** [comment]
non : "imagery" ça fait en général référence aux photos satellitales. Donc pas très précises ni géométriquement ni en résolution. Au contraire de "orthoimagery" : photos rectifiées et beaucoup plus précises en positionnement. Le vecteur d'acquisition est généralement différent.

"basemap" = fond de plan, donc le reste.

"unknown" = je ne sais pas . C'est différent de "other" qui veut dire : je sais mais la liste des valeurs ne correspond pas.

**Comment by yohanboniface** [comment]
OK.
Personnellement, je pense que si on a des valeurs trop précises, alors on aura une faible qualité de remplissage de ce champ. Par exemple, y a sûrement plein de situations où un client ne saura pas clairement faire la différence entre `imagery`, `basemap` et `orthoimagery`, et on risque de se retrouver avec des mauvaises valeurs.
J'avais déjà fait cette remarque lors de l'atelier, à propos des différentes valeurs de calcul, en suggérant plutôt qu'on ait qu'une valeur qui dit "calculée", et ensuite si quelqu'un veut être plus précis il peut utiliser les `attributes`.

Une autre approche pourrait être d'avoir à la place un champ `precision` où on définit la précision estimée du positionnement: en dessous du mètre, au mètre, supérieur au mètre, supérieur à 10 mètres?

**Comment by MaelREBOUX** [comment]
Si un gestionnaire d'adresses qui veut contribuer à la BAN ne sait pas la différence entre imagery, basemap et orthoimagery... Comment dire... 

Si on va sur la qualité de positionnement via la précision, cela devient une usine à gaz qui sera difficile à maintenir. On ne peut pas cautionner ça à la légère.

Concrètement : on préfère souhaiter ne pas voir cet attribut dans la BAN. Actuellement.

**Comment by cquest** [comment]
Il faut rester proche d'INSPIRE.

Un attribut qui donne une indication de précision et/ou de méthode qui a permis d'avoir un X/Y me semble indispensable... sinon comment juger entre 2 positions laquelle est potentiellement la meilleure ?

Exemple: http://tile.openstreetmap.fr/~cquest/leaflet/bano.html#19/48.84669/2.27861

**Comment by ebuard** [comment]
Pour la prod du 30 juin, nous proposons de conserver ces valeurs et de fermer ce ticket.
Pour la suite, on pourra revenir dessus suite à cette première prod.
